"""Initial baseline migration

Revision ID: 91b9a61fcafa
Revises: 
Create Date: 2025-11-04 10:44:25.856525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b9a61fcafa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('agent_type', sa.Enum('dev_agent', 'ops_agent', 'pm_agent', 'growth_strategist', 'meta_agent', name='agenttypedb'), nullable=False),
    sa.Column('status', sa.Enum('active', 'idle', 'busy', 'offline', 'error', name='agentstatusdb'), nullable=False),
    sa.Column('permission_level', sa.Enum('sandbox_only', 'staging_access', 'prod_low_risk', 'prod_full_access', name='permissionleveldb'), nullable=False),
    sa.Column('reputation_score', sa.Integer(), nullable=False),
    sa.Column('capabilities', sa.Text(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('pr_merged_count', sa.Integer(), nullable=False),
    sa.Column('pr_reverted_count', sa.Integer(), nullable=False),
    sa.Column('test_pass_count', sa.Integer(), nullable=False),
    sa.Column('test_fail_count', sa.Integer(), nullable=False),
    sa.Column('test_pass_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('queued', 'assigned', 'running', 'completed', 'failed', 'cancelled', name='taskstatusdb'), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('user')
    op.drop_table('agents')
    # ### end Alembic commands ###
