"""Initial baseline migration

Revision ID: 91b9a61fcafa
Revises: 
Create Date: 2025-11-04 10:44:25.856525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b9a61fcafa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('agent_type', sa.Enum('DEV_AGENT', 'OPS_AGENT', 'PM_AGENT', 'GROWTH_STRATEGIST', 'META_AGENT', name='agenttypedb'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'IDLE', 'BUSY', 'OFFLINE', 'ERROR', name='agentstatusdb'), nullable=False),
    sa.Column('permission_level', sa.Enum('SANDBOX_ONLY', 'STAGING_ACCESS', 'PROD_LOW_RISK', 'PROD_FULL_ACCESS', name='permissionleveldb'), nullable=False),
    sa.Column('reputation_score', sa.Integer(), nullable=False),
    sa.Column('capabilities', sa.Text(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('pr_merged_count', sa.Integer(), nullable=False),
    sa.Column('pr_reverted_count', sa.Integer(), nullable=False),
    sa.Column('test_pass_count', sa.Integer(), nullable=False),
    sa.Column('test_fail_count', sa.Integer(), nullable=False),
    sa.Column('test_pass_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'ASSIGNED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatusdb'), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.drop_table('user_stories')
    op.drop_table('beta_candidates')
    op.drop_table('report_templates')
    op.drop_table('approval_requests')
    op.drop_table('gamification_rules')
    op.drop_table('dashboard_layouts')
    op.drop_table('state_checkpoints')
    op.drop_table('report_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_history',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('type', sa.TEXT(), nullable=False),
    sa.Column('format', sa.TEXT(), nullable=False),
    sa.Column('file_path', sa.TEXT(), nullable=True),
    sa.Column('generated_at', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state_checkpoints',
    sa.Column('checkpoint_id', sa.TEXT(), nullable=True),
    sa.Column('component_name', sa.TEXT(), nullable=False),
    sa.Column('state_data', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.Column('metadata', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('checkpoint_id')
    )
    op.create_table('dashboard_layouts',
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('layout_config', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('gamification_rules',
    sa.Column('rule_id', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('trigger_condition', sa.TEXT(), nullable=False),
    sa.Column('reward_type', sa.TEXT(), nullable=False),
    sa.Column('reward_amount', sa.INTEGER(), nullable=False),
    sa.Column('effectiveness_score', sa.REAL(), nullable=False),
    sa.Column('last_updated', sa.TEXT(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('approval_requests',
    sa.Column('request_id', sa.TEXT(), nullable=True),
    sa.Column('trace_id', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('context', sa.TEXT(), nullable=False),
    sa.Column('prompt_details', sa.TEXT(), nullable=False),
    sa.Column('requester_agent', sa.TEXT(), nullable=False),
    sa.Column('priority', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.Column('expires_at', sa.TEXT(), nullable=False),
    sa.Column('approved_by', sa.TEXT(), nullable=True),
    sa.Column('approved_at', sa.TEXT(), nullable=True),
    sa.Column('approval_channel', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('report_templates',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('type', sa.TEXT(), nullable=False),
    sa.Column('config', sa.TEXT(), nullable=False),
    sa.Column('created_by', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beta_candidates',
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('activity_score', sa.REAL(), nullable=False),
    sa.Column('engagement_metrics', sa.TEXT(), nullable=False),
    sa.Column('qualification_reason', sa.TEXT(), nullable=False),
    sa.Column('invited_at', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_stories',
    sa.Column('story_id', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('priority', sa.TEXT(), nullable=False),
    sa.Column('estimated_effort', sa.INTEGER(), nullable=False),
    sa.Column('source_feedback', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'backlog'"), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('story_id')
    )
    op.drop_table('tasks')
    op.drop_table('user')
    op.drop_table('agents')
    # ### end Alembic commands ###
