app = "morningai-web"
primary_region = "nrt"

[build]
  dockerfile = ".fly-web/Dockerfile"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443
