packages:
  # Frontend applications
  - 'frontend-dashboard-deploy'
  - 'handoff/20250928/40_App/frontend-dashboard'
  - 'handoff/20250928/40_App/owner-console'
  
  # Future shared packages (when created)
  # - 'packages/*'
