services:
  - type: web
    name: morningai-api
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      cd handoff/20250928/40_App/morningai_enhanced/api-backend &&
      pip install -r requirements.txt
    startCommand: |
      cd handoff/20250928/40_App/morningai_enhanced/api-backend &&
      python start_server.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: API_BASE_URL
        value: https://morningai-api.onrender.com
      - key: PORT
        value: 10000
      - key: FLASK_SECRET_KEY
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: SENTRY_AUTH_TOKEN
        sync: false
      - key: CLOUDFLARE_API_TOKEN
        sync: false
      - key: CLOUDFLARE_ZONE_ID
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: VERCEL_TOKEN
        sync: false
      - key: VERCEL_ORG_ID
        sync: false
      - key: VERCEL_PROJECT_ID
        sync: false
      - key: RENDER_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
