services:
  - type: web
    name: morningai-backend
    env: python
    buildCommand: pip install -r handoff/20250928/40_App/api-backend/requirements.txt
    startCommand: cd handoff/20250928/40_App/api-backend/src && gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///database/morningai.db
      - key: REDIS_URL
        value: redis://localhost:6379/0
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
