-- Migration 024: Create planner_events table for Phase 1 monitoring
--
-- This table stores planner execution metrics for agent_eval and monitoring.
-- Replaces ephemeral local JSONL files with persistent database storage.
--
-- Related: PR #1616 (planner statistics CLI tool)

CREATE TABLE IF NOT EXISTS planner_events (
    id BIGSERIAL PRIMARY KEY,
    trace_id UUID NOT NULL,
    goal TEXT NOT NULL,
    planner_type VARCHAR(50) NOT NULL,
    task_type VARCHAR(100),
    actual_plan_steps JSONB NOT NULL,
    num_steps INTEGER NOT NULL,
    planning_time_ms DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_planner_events_timestamp 
    ON planner_events(timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_planner_events_trace_id 
    ON planner_events(trace_id);

CREATE INDEX IF NOT EXISTS idx_planner_events_planner_type_timestamp 
    ON planner_events(planner_type, timestamp DESC);

-- Comments for documentation
COMMENT ON TABLE planner_events IS 
    'Planner execution metrics for Phase 1 monitoring and agent_eval analytics';

COMMENT ON COLUMN planner_events.trace_id IS 
    'Unique identifier for the task/trace (correlates with agent_tasks)';

COMMENT ON COLUMN planner_events.planner_type IS 
    'Type of planner used (e.g., "llm", "simple", "hybrid")';

COMMENT ON COLUMN planner_events.task_type IS 
    'Classification of the task (e.g., "codegen", "bugfix", "refactor")';

COMMENT ON COLUMN planner_events.actual_plan_steps IS 
    'JSON array of plan steps generated by the planner';

COMMENT ON COLUMN planner_events.planning_time_ms IS 
    'Time taken to generate the plan in milliseconds';

COMMENT ON COLUMN planner_events.timestamp IS 
    'When the plan was generated (from planner, not DB insert time)';

COMMENT ON INDEX idx_planner_events_timestamp IS 
    'Performance index for time-range queries (--last N, date filters)';

COMMENT ON INDEX idx_planner_events_trace_id IS 
    'Performance index for trace-based lookups and correlation';

COMMENT ON INDEX idx_planner_events_planner_type_timestamp IS 
    'Composite index for planner-type filtered time-range queries';
