#!/usr/bin/env node
/**
 * Design Tokens Compiler
 * Converts tokens.json to Tailwind CSS variables and TypeScript types
 * Part of UX Ops Pipeline - Priority 1
 */

const fs = require('fs');
const path = require('path');

const TOKENS_PATH = path.join(__dirname, '../src/tokens.json');
const OUTPUT_CSS_PATH = path.join(__dirname, '../dist/tokens.css');
const OUTPUT_TS_PATH = path.join(__dirname, '../dist/tokens.d.ts');

function loadTokens() {
  const tokensContent = fs.readFileSync(TOKENS_PATH, 'utf-8');
  return JSON.parse(tokensContent);
}

function generateCSSVariables(tokens, prefix = '') {
  let css = '';
  
  for (const [key, value] of Object.entries(tokens)) {
    // Special handling for "base" tokens - generate without "base-" prefix
    // These are the tokens that Tailwind v4 utilities like bg-primary expect
    if (key === 'base' && typeof value === 'object') {
      for (const [baseKey, baseValue] of Object.entries(value)) {
        css += `  --color-${baseKey}: ${baseValue};\n`;
      }
      continue;
    }
    
    const varName = prefix ? `${prefix}-${key}` : key;
    
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      css += generateCSSVariables(value, varName);
    } else {
      css += `  --${varName}: ${value};\n`;
    }
  }
  
  return css;
}

function generateTailwindConfig(tokens) {
  const config = {
    colors: {},
    spacing: {},
    borderRadius: {},
    boxShadow: {},
    fontFamily: {},
    fontSize: {},
    fontWeight: {},
    lineHeight: {},
    transitionDuration: {},
    transitionTimingFunction: {},
    screens: {}
  };

  if (tokens.color) {
    config.colors = {
      primary: tokens.color.primary,
      accent: tokens.color.accent,
      semantic: tokens.color.semantic,
      neutral: tokens.color.neutral,
      background: tokens.color.background
    };
  }

  if (tokens.space) {
    config.spacing = tokens.space;
  }

  if (tokens.radius) {
    config.borderRadius = tokens.radius;
  }

  if (tokens.shadow) {
    config.boxShadow = tokens.shadow;
  }

  if (tokens.font) {
    config.fontFamily = tokens.font.family;
    config.fontSize = tokens.font.size;
    config.fontWeight = tokens.font.weight;
    config.lineHeight = tokens.font.lineHeight;
  }

  if (tokens.animation) {
    config.transitionDuration = tokens.animation.duration;
    config.transitionTimingFunction = tokens.animation.easing;
  }

  if (tokens.breakpoint) {
    config.screens = tokens.breakpoint;
  }

  return config;
}

function generateTypeScript(tokens) {
  let ts = `/**
 * Auto-generated TypeScript types for design tokens
 * DO NOT EDIT MANUALLY - Generated by compile-tokens.js
 */

export interface DesignTokens {
  color: {
    primary: ColorScale;
    accent: {
      purple: ColorScale;
      orange: ColorScale;
    };
    semantic: {
      success: ColorScaleWithAAA;
      error: ColorScaleWithAAA;
      warning: ColorScaleWithAAA;
      info: ColorScaleWithAAA;
    };
    neutral: ColorScale;
    background: {
      base: string;
      surface: string;
      overlay: string;
    };
  };
  font: {
    family: {
      primary: string;
      secondary: string;
      mono: string;
    };
    size: Record<string, string>;
    lineHeight: Record<string, string>;
    weight: Record<string, string>;
  };
  space: Record<string, string>;
  radius: Record<string, string>;
  shadow: Record<string, string>;
  animation: {
    duration: Record<string, string>;
    easing: Record<string, string>;
  };
  breakpoint: Record<string, string>;
  accessibility: {
    "wcag-aaa": {
      contrast: Record<string, string>;
      colors: Record<string, string>;
    };
    focus: {
      "outline-width": string;
      "outline-offset": string;
      "outline-color": string;
    };
    "touch-target": {
      "min-size": string;
    };
    animation: {
      "reduced-motion-duration": string;
    };
  };
}

interface ColorScale {
  50: string;
  100: string;
  200: string;
  300: string;
  400: string;
  500: string;
  600: string;
  700: string;
  800: string;
  900: string;
}

interface ColorScaleWithAAA extends ColorScale {
  "text-aaa": string;
}

declare const tokens: DesignTokens;
export default tokens;
`;

  return ts;
}

function compile() {
  console.log('🎨 Compiling design tokens...');
  
  const tokens = loadTokens();
  console.log('✓ Loaded tokens.json');

  const cssVariables = `:root {\n${generateCSSVariables(tokens)}}\n`;
  fs.mkdirSync(path.dirname(OUTPUT_CSS_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_CSS_PATH, cssVariables);
  console.log(`✓ Generated CSS variables: ${OUTPUT_CSS_PATH}`);

  const tailwindConfig = generateTailwindConfig(tokens);
  const tailwindConfigPath = path.join(__dirname, '../dist/tailwind.config.snippet.json');
  fs.writeFileSync(tailwindConfigPath, JSON.stringify(tailwindConfig, null, 2));
  console.log(`✓ Generated Tailwind config: ${tailwindConfigPath}`);

  const tsTypes = generateTypeScript(tokens);
  fs.writeFileSync(OUTPUT_TS_PATH, tsTypes);
  console.log(`✓ Generated TypeScript types: ${OUTPUT_TS_PATH}`);

  console.log('✨ Token compilation complete!');
}

try {
  compile();
} catch (error) {
  console.error('❌ Token compilation failed:', error);
  process.exit(1);
}
