openapi: 3.0.3
info:
  title: MorningAI API
  version: 1.0.0
servers:
  - url: https://api.morningai.dev/v1
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: ok
  /agents:
    get:
      summary: List agents
      responses:
        '200':
          description: ok
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
