
ALTER TABLE user ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE user ADD COLUMN IF NOT EXISTS preferences TEXT DEFAULT '{}';

UPDATE user SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;

UPDATE user SET preferences = '{}' WHERE preferences IS NULL;
