#!/usr/bin/env python3
"""
Generate ENV_REFERENCE.md from config/env.schema.yaml

This script reads the canonical environment schema and generates
a categorized reference document with security levels and descriptions.

Usage:
    python scripts/generate-env-reference.py
"""

import yaml
import sys
from pathlib import Path
from typing import Dict, Any, List, Tuple
from collections import defaultdict

from repo_root_utils import get_repo_root


SECURITY_LEVEL_EMOJI = {
    'critical': 'CRITICAL',
    'secret': 'SECRET',
    'medium': 'MEDIUM',
    'low': 'LOW',
    'public': 'PUBLIC',
}


def load_schema(schema_path: Path) -> Dict[str, Any]:
    """Load the environment schema from YAML file."""
    with open(schema_path, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)


def categorize_fields(fields: Dict[str, Any]) -> Dict[str, List[Tuple[str, Dict[str, Any]]]]:
    """Categorize fields by their category."""
    categorized = defaultdict(list)
    for var_name, var_config in fields.items():
        category = var_config.get('category', 'Other')
        categorized[category].append((var_name, var_config))
    return categorized


def format_type(var_config: Dict[str, Any]) -> str:
    """Format the type string for a variable."""
    var_type = var_config.get('type', 'string')
    choices = var_config.get('choices', [])
    if choices:
        return f"{var_type} ({', '.join(str(c) for c in choices)})"
    return var_type


def format_default(var_config: Dict[str, Any], include_env_specific: bool = False) -> str:
    """Format the default value for a variable.

    Args:
        var_config: Variable configuration dictionary
        include_env_specific: If True, append environment-specific values

    Returns:
        Formatted default value string
    """
    default = var_config.get('default')
    if default is None:
        base = '-'
    elif isinstance(default, bool):
        base = str(default).lower()
    else:
        base = str(default)

    if include_env_specific:
        env_specific = var_config.get('environment_specific')
        if env_specific:
            env_parts = [f"{env}={val}" for env, val in env_specific.items()]
            return f"{base} ({', '.join(env_parts)})"

    return base


def generate_env_reference(schema: Dict[str, Any], output_path: Path) -> None:
    """Generate the ENV_REFERENCE.md file."""
    lines = []

    lines.append("# Environment Variable Reference")
    lines.append("")
    lines.append("> Auto-generated from `config/env.schema.yaml`")
    lines.append("> DO NOT EDIT THIS FILE MANUALLY - Run `python scripts/generate-env-reference.py` instead")
    lines.append("")

    fields = schema.get('fields', {})
    total_count = len(fields)
    required_count = sum(1 for v in fields.values() if v.get('required', False))
    optional_count = total_count - required_count

    lines.append("## Overview")
    lines.append("")
    lines.append(f"- **Schema Version**: {schema.get('version', 'unknown')}")
    lines.append(f"- **Total Variables**: {total_count}")
    lines.append(f"- **Required**: {required_count}")
    lines.append(f"- **Optional**: {optional_count}")
    lines.append(f"- **Last Updated**: {schema.get('metadata', {}).get('last_updated', 'unknown')}")
    lines.append("")

    lines.append("## Security Levels")
    lines.append("")
    lines.append("| Level | Description |")
    lines.append("|-------|-------------|")
    lines.append("| CRITICAL | Must never be exposed. Rotation required if leaked. |")
    lines.append("| SECRET | Sensitive credentials. Should not be logged. |")
    lines.append("| MEDIUM | Internal configuration. Limited exposure risk. |")
    lines.append("| LOW | Non-sensitive operational settings. |")
    lines.append("| PUBLIC | Safe to expose. No security impact. |")
    lines.append("")

    categorized = categorize_fields(fields)

    category_order = [
        'Authentication',
        'Security',
        'Database',
        'Cloud Services',
        'Infrastructure',
        'Monitoring',
        'Integration',
        'Worker',
        'Application',
        'Feature Flags',
        'Orchestrator',
        'Frontend',
        'Testing',
        'Payment',
        'Agent Evaluation',
        'Deployment',
        'Debugging',
    ]

    lines.append("## Table of Contents")
    lines.append("")
    for category in category_order:
        if category in categorized:
            anchor = category.lower().replace(' ', '-')
            count = len(categorized[category])
            lines.append(f"- [{category}](#{anchor}) ({count} variables)")
    lines.append("")

    for category in category_order:
        if category not in categorized:
            continue

        vars_in_category = categorized[category]
        lines.append(f"## {category}")
        lines.append("")

        lines.append("| Variable | Type | Required | Default | Security |")
        lines.append("|----------|------|----------|---------|----------|")

        for var_name, var_config in vars_in_category:
            var_type = format_type(var_config)
            required = "Yes" if var_config.get('required', False) else "No"
            default = format_default(var_config, include_env_specific=True)
            security = SECURITY_LEVEL_EMOJI.get(
                var_config.get('security_level', 'public'), 'PUBLIC'
            )
            lines.append(f"| `{var_name}` | {var_type} | {required} | {default} | {security} |")

        lines.append("")

        lines.append("### Details")
        lines.append("")

        for var_name, var_config in vars_in_category:
            lines.append(f"#### `{var_name}`")
            lines.append("")

            description = var_config.get('description', 'No description available.')
            lines.append(f"{description}")
            lines.append("")

            lines.append(f"- **Type**: {format_type(var_config)}")
            lines.append(f"- **Required**: {'Yes' if var_config.get('required', False) else 'No'}")
            lines.append(f"- **Default**: `{format_default(var_config)}`")
            lines.append(f"- **Security Level**: {SECURITY_LEVEL_EMOJI.get(var_config.get('security_level', 'public'), 'PUBLIC')}")

            example = var_config.get('example')
            if example:
                lines.append(f"- **Example**: `{example}`")

            notes = var_config.get('notes')
            if notes:
                lines.append("")
                lines.append("**Notes**:")
                for note_line in notes.strip().split('\n'):
                    stripped = note_line.strip()
                    if stripped:
                        lines.append(f"> {stripped}")

            env_specific = var_config.get('environment_specific')
            if env_specific:
                lines.append("")
                lines.append("**Environment-specific values**:")
                for env, value in env_specific.items():
                    lines.append(f"- {env}: `{value}`")

            lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f"Generated: {output_path}")


def main():
    """Main entry point."""
    repo_root = get_repo_root()
    schema_path = repo_root / 'config' / 'env.schema.yaml'

    if not schema_path.exists():
        print(f"Schema file not found: {schema_path}")
        sys.exit(1)

    print(f"Loading schema from: {schema_path}")
    schema = load_schema(schema_path)

    fields = schema.get('fields', {})
    total_count = len(fields)
    required_count = sum(1 for v in fields.values() if v.get('required', False))
    optional_count = total_count - required_count

    print(f"Schema version: {schema.get('version')}")
    print(f"Total variables: {total_count} ({required_count} required, {optional_count} optional)")
    print("")

    output_path = repo_root / 'docs' / 'ENV_REFERENCE.md'
    generate_env_reference(schema, output_path)

    print("")
    print("ENV_REFERENCE.md generated successfully!")
    print("")
    print("Next steps:")
    print("   1. Review generated file")
    print("   2. Commit changes to git")


if __name__ == '__main__':
    main()
