#!/usr/bin/env python3
"""
Generate .env.example files from config/env.schema.yaml

This script reads the canonical environment schema and generates
.env.example files for different components of the application.

Usage:
    python scripts/generate-env-examples.py
"""

import yaml
import sys
from pathlib import Path
from typing import Dict, Any, List

from repo_root_utils import get_repo_root


def load_schema(schema_path: Path) -> Dict[str, Any]:
    """Load the environment schema from YAML file."""
    with open(schema_path, 'r') as f:
        return yaml.safe_load(f)


def generate_env_example(schema: Dict[str, Any], categories: List[str], output_path: Path) -> None:
    """Generate a .env.example file for specific categories."""
    lines = []
    lines.append("# Generated from config/env.schema.yaml")
    lines.append("# DO NOT EDIT THIS FILE MANUALLY - Run scripts/generate-env-examples.py instead")
    lines.append("")
    
    fields = schema.get('fields', {})
    
    categorized_fields = {}
    for var_name, var_config in fields.items():
        category = var_config.get('category', 'Other')
        if category not in categorized_fields:
            categorized_fields[category] = []
        categorized_fields[category].append((var_name, var_config))
    
    for category in categories:
        if category not in categorized_fields:
            continue
            
        lines.append(f"# {category}")
        lines.append("")
        
        for var_name, var_config in categorized_fields[category]:
            description = var_config.get('description', '')
            if description:
                lines.append(f"# {description}")
            
            notes = var_config.get('notes', '')
            if notes:
                for note_line in notes.strip().split('\n'):
                    lines.append(f"# {note_line.strip()}")
            
            required = var_config.get('required', False)
            lines.append(f"# Required: {required}")
            
            example = var_config.get('example', '')
            default = var_config.get('default', '')
            
            if example:
                lines.append(f"{var_name}={example}")
            elif default:
                lines.append(f"{var_name}={default}")
            else:
                var_type = var_config.get('type', 'string')
                if var_type == 'secret':
                    lines.append(f"{var_name}=your-secret-here")
                elif var_type == 'url':
                    lines.append(f"{var_name}=https://example.com")
                elif var_type == 'boolean':
                    lines.append(f"{var_name}=false")
                elif var_type == 'integer':
                    lines.append(f"{var_name}=0")
                else:
                    lines.append(f"{var_name}=")
            
            lines.append("")
    
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))
    
    print(f"✅ Generated: {output_path}")


def main():
    """Main entry point."""
    repo_root = get_repo_root()
    schema_path = repo_root / 'config' / 'env.schema.yaml'
    
    if not schema_path.exists():
        print(f"❌ Schema file not found: {schema_path}")
        sys.exit(1)
    
    print(f"📖 Loading schema from: {schema_path}")
    schema = load_schema(schema_path)
    
    fields = schema.get('fields', {})
    total_count = len(fields)
    required_count = sum(1 for v in fields.values() if v.get('required', False))
    optional_count = total_count - required_count
    
    print(f"📊 Schema version: {schema.get('version')}")
    print(f"📊 Total variables: {total_count} ({required_count} required, {optional_count} optional)")
    print("")
    
    backend_categories = [
        'Authentication',
        'Security',
        'Database',
        'Cloud Services',
        'Infrastructure',
        'Monitoring',
        'Integration',
        'Worker',
        'Application',
        'Feature Flags',
        'Deployment',
        'Testing',
    ]
    
    generate_env_example(
        schema,
        backend_categories,
        repo_root / '.env.example'
    )
    
    generate_env_example(
        schema,
        backend_categories,
        repo_root / 'handoff' / '20250928' / '40_App' / 'api-backend' / '.env.example'
    )
    
    frontend_categories = ['Frontend', 'Application', 'Feature Flags']
    generate_env_example(
        schema,
        frontend_categories,
        repo_root / 'handoff' / '20250928' / '40_App' / 'frontend-dashboard' / '.env.example'
    )
    
    generate_env_example(
        schema,
        frontend_categories,
        repo_root / 'handoff' / '20250928' / '40_App' / 'owner-console' / '.env.example'
    )
    
    orchestrator_categories = ['Database', 'Application', 'Integration', 'Worker', 'Feature Flags', 'Deployment']
    generate_env_example(
        schema,
        orchestrator_categories,
        repo_root / 'orchestrator' / '.env.example'
    )
    
    print("")
    print("✅ All .env.example files generated successfully!")
    print("")
    print("📝 Next steps:")
    print("   1. Review generated files")
    print("   2. Commit changes to git")
    print("   3. Update CI to check for drift (scripts/check-env-drift.py)")


if __name__ == '__main__':
    main()
