#!/usr/bin/env python3
"""
MorningAI Reviewer Stability Scorecard

This tool calculates reviewer stability metrics using the GitHub API.
It is part of EPIC B's governance measurement layer, used to determine:
- When to enable production flags
- When to proceed to EPIC C (Flow Controller)
- Future P6 (Checks API/status gate) integration

Usage:
    GITHUB_TOKEN=xxx python tools/reviewer_stability_scorecard.py [--days 7] [--output json|markdown]

Environment Variables:
    GITHUB_TOKEN: GitHub personal access token with repo read access
    GITHUB_REPO: Repository in owner/repo format (default: RC918/morningai)

Metrics Calculated:
    - Review count per PR
    - Duplicate review detection (same commit_id reviewed multiple times)
    - Review coverage (PRs with at least one MorningAI review)
    - Review latency (time from PR open/push to review)
"""

import argparse
import json
import os
import sys
from collections import defaultdict
from datetime import datetime, timedelta, timezone
# Note: typing imports removed - using built-in types for Python 3.9+

try:
    import requests
except ImportError:
    print("ERROR: requests library required. Install with: pip install requests")
    sys.exit(1)

# MorningAI review marker - must match orchestrator/utils/constants.py
MORNINGAI_REVIEW_MARKER = "<!-- morningai:autogen-review -->"

# Default configuration
DEFAULT_REPO = "RC918/morningai"
DEFAULT_DAYS = 7
API_BASE = "https://api.github.com"


class GitHubAPIError(Exception):
    """Custom exception for GitHub API errors."""

    pass


def get_headers(token: str) -> dict:
    """Get headers for GitHub API requests."""
    return {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def get_recent_prs(
    token: str, repo: str, days: int, state: str = "all"
) -> list:
    """Get PRs updated within the specified number of days."""
    url = f"{API_BASE}/repos/{repo}/pulls"
    since = datetime.now(timezone.utc) - timedelta(days=days)

    all_prs = []
    page = 1
    per_page = 100

    while True:
        params = {
            "state": state,
            "sort": "updated",
            "direction": "desc",
            "per_page": per_page,
            "page": page,
        }

        resp = requests.get(url, headers=get_headers(token), params=params)
        if resp.status_code != 200:
            raise GitHubAPIError(f"Failed to fetch PRs: {resp.status_code} {resp.text}")

        prs = resp.json()
        if not prs:
            break

        for pr in prs:
            updated_at = datetime.fromisoformat(pr["updated_at"].replace("Z", "+00:00"))
            if updated_at < since:
                return all_prs
            all_prs.append(pr)

        if len(prs) < per_page:
            break
        page += 1

    return all_prs


def get_pr_reviews(token: str, repo: str, pr_number: int) -> list:
    """Get all reviews for a specific PR."""
    url = f"{API_BASE}/repos/{repo}/pulls/{pr_number}/reviews"

    all_reviews = []
    page = 1
    per_page = 100

    while True:
        params = {"per_page": per_page, "page": page}
        resp = requests.get(url, headers=get_headers(token), params=params)
        if resp.status_code != 200:
            raise GitHubAPIError(
                f"Failed to fetch reviews for PR #{pr_number}: {resp.status_code}"
            )

        reviews = resp.json()
        if not reviews:
            break

        all_reviews.extend(reviews)
        if len(reviews) < per_page:
            break
        page += 1

    return all_reviews


def is_morningai_review(review: dict) -> bool:
    """Check if a review was generated by MorningAI.

    Detection methods (in order of reliability):
    1. Check for marker in review body
    2. Check for marker in review comments (if body is empty)
    """
    body = review.get("body") or ""
    if MORNINGAI_REVIEW_MARKER in body:
        return True

    # Some reviews may have the marker in the first comment instead
    # This is a fallback check
    return False


def calculate_metrics(
    token: str, repo: str, days: int
) -> dict:
    """Calculate reviewer stability metrics."""
    print(f"Fetching PRs from {repo} updated in last {days} days...")
    prs = get_recent_prs(token, repo, days)
    print(f"Found {len(prs)} PRs")

    metrics = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "repo": repo,
        "days_analyzed": days,
        "total_prs": len(prs),
        "prs_with_morningai_review": 0,
        "total_morningai_reviews": 0,
        "duplicate_reviews": 0,
        "duplicate_commits": [],
        "review_latencies_seconds": [],
        "prs_analyzed": [],
    }

    # Track reviews by commit_id for duplicate detection
    reviews_by_commit: dict = defaultdict(list)

    for pr in prs:
        pr_number = pr["number"]
        pr_title = pr["title"][:50]
        pr_created_at = datetime.fromisoformat(
            pr["created_at"].replace("Z", "+00:00")
        )
        head_sha = pr["head"]["sha"]

        print(f"  Analyzing PR #{pr_number}: {pr_title}...")

        try:
            reviews = get_pr_reviews(token, repo, pr_number)
        except GitHubAPIError as e:
            print(f"    Warning: {e}")
            continue

        morningai_reviews = [r for r in reviews if is_morningai_review(r)]

        pr_info = {
            "number": pr_number,
            "title": pr_title,
            "state": pr["state"],
            "head_sha": head_sha[:7],
            "total_reviews": len(reviews),
            "morningai_reviews": len(morningai_reviews),
            "morningai_review_commits": [],
        }

        if morningai_reviews:
            metrics["prs_with_morningai_review"] += 1
            metrics["total_morningai_reviews"] += len(morningai_reviews)

            for review in morningai_reviews:
                commit_id = review.get("commit_id", "unknown")
                submitted_at_str = review.get("submitted_at")

                pr_info["morningai_review_commits"].append(commit_id[:7])
                reviews_by_commit[commit_id].append({
                    "pr_number": pr_number,
                    "review_id": review["id"],
                    "submitted_at": submitted_at_str,
                })

                # Calculate latency from PR creation to review
                if submitted_at_str:
                    submitted_at = datetime.fromisoformat(
                        submitted_at_str.replace("Z", "+00:00")
                    )
                    latency = (submitted_at - pr_created_at).total_seconds()
                    if latency > 0:
                        metrics["review_latencies_seconds"].append(latency)

        metrics["prs_analyzed"].append(pr_info)

    # Calculate duplicate reviews (same commit reviewed multiple times)
    for commit_id, reviews_list in reviews_by_commit.items():
        if len(reviews_list) > 1:
            metrics["duplicate_reviews"] += len(reviews_list) - 1
            metrics["duplicate_commits"].append({
                "commit_id": commit_id[:7],
                "review_count": len(reviews_list),
                "pr_numbers": [r["pr_number"] for r in reviews_list],
            })

    # Calculate summary statistics
    if metrics["total_prs"] > 0:
        metrics["review_coverage_percent"] = round(
            100 * metrics["prs_with_morningai_review"] / metrics["total_prs"], 1
        )
    else:
        metrics["review_coverage_percent"] = 0.0

    if metrics["review_latencies_seconds"]:
        latencies = metrics["review_latencies_seconds"]
        metrics["avg_latency_seconds"] = round(sum(latencies) / len(latencies), 1)
        metrics["min_latency_seconds"] = round(min(latencies), 1)
        metrics["max_latency_seconds"] = round(max(latencies), 1)
    else:
        metrics["avg_latency_seconds"] = None
        metrics["min_latency_seconds"] = None
        metrics["max_latency_seconds"] = None

    # Calculate duplicate rate
    total_reviewed_commits = len(reviews_by_commit)
    if total_reviewed_commits > 0:
        duplicate_commit_count = len(metrics["duplicate_commits"])
        metrics["duplicate_rate_percent"] = round(
            100 * duplicate_commit_count / total_reviewed_commits, 1
        )
    else:
        metrics["duplicate_rate_percent"] = 0.0

    # Health score calculation
    # Lower is better: penalize duplicates heavily, reward coverage
    health_score = 0
    health_score += metrics["duplicate_reviews"] * 50  # Heavy penalty for duplicates
    health_score -= metrics["review_coverage_percent"]  # Reward coverage
    if metrics["avg_latency_seconds"] and metrics["avg_latency_seconds"] > 300:
        health_score += 10  # Penalty for slow reviews (>5 min avg)

    metrics["health_score"] = max(0, health_score)

    if metrics["health_score"] == 0 and metrics["duplicate_reviews"] == 0:
        metrics["status"] = "EXCELLENT"
    elif metrics["health_score"] < 50:
        metrics["status"] = "GOOD"
    elif metrics["health_score"] < 100:
        metrics["status"] = "FAIR"
    else:
        metrics["status"] = "NEEDS ATTENTION"

    return metrics


def format_markdown(metrics: dict) -> str:
    """Format metrics as Markdown report."""
    lines = [
        "# MorningAI Reviewer Stability Scorecard",
        "",
        f"**Generated:** {metrics['generated_at']}",
        f"**Repository:** {metrics['repo']}",
        f"**Analysis Period:** Last {metrics['days_analyzed']} days",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total PRs Analyzed | {metrics['total_prs']} |",
        f"| PRs with MorningAI Review | {metrics['prs_with_morningai_review']} |",
        f"| Review Coverage | {metrics['review_coverage_percent']}% |",
        f"| Total MorningAI Reviews | {metrics['total_morningai_reviews']} |",
        f"| Duplicate Reviews | {metrics['duplicate_reviews']} |",
        f"| Duplicate Rate | {metrics['duplicate_rate_percent']}% |",
        "",
    ]

    if metrics["avg_latency_seconds"] is not None:
        lines.extend([
            "## Review Latency",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Average | {metrics['avg_latency_seconds']:.0f}s |",
            f"| Minimum | {metrics['min_latency_seconds']:.0f}s |",
            f"| Maximum | {metrics['max_latency_seconds']:.0f}s |",
            "",
        ])

    if metrics["duplicate_commits"]:
        lines.extend([
            "## Duplicate Reviews (Needs Investigation)",
            "",
            "| Commit | Review Count | PRs |",
            "|--------|--------------|-----|",
        ])
        for dup in metrics["duplicate_commits"]:
            pr_list = ", ".join(f"#{n}" for n in dup["pr_numbers"])
            lines.append(
                f"| {dup['commit_id']} | {dup['review_count']} | {pr_list} |"
            )
        lines.append("")

    lines.extend([
        "## Health Assessment",
        "",
        f"**Health Score:** {metrics['health_score']} (lower is better)",
        f"**Status:** {metrics['status']}",
        "",
        "### Scoring Criteria",
        "",
        "- Each duplicate review: +50 points",
        "- Review coverage: -1 point per % coverage",
        "- Slow reviews (>5 min avg): +10 points",
        "",
        "### Status Thresholds",
        "",
        "- EXCELLENT: Score = 0, no duplicates",
        "- GOOD: Score < 50",
        "- FAIR: Score < 100",
        "- NEEDS ATTENTION: Score >= 100",
    ])

    return "\n".join(lines)


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="MorningAI Reviewer Stability Scorecard"
    )
    parser.add_argument(
        "--days",
        type=int,
        default=DEFAULT_DAYS,
        help=f"Number of days to analyze (default: {DEFAULT_DAYS})",
    )
    parser.add_argument(
        "--output",
        choices=["json", "markdown", "both"],
        default="both",
        help="Output format (default: both)",
    )
    parser.add_argument(
        "--repo",
        type=str,
        default=None,
        help=f"Repository in owner/repo format (default: {DEFAULT_REPO})",
    )
    args = parser.parse_args()

    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        print("ERROR: GITHUB_TOKEN environment variable not set")
        sys.exit(1)

    repo = args.repo or os.environ.get("GITHUB_REPO", DEFAULT_REPO)

    try:
        metrics = calculate_metrics(token, repo, args.days)
    except GitHubAPIError as e:
        print(f"ERROR: {e}")
        sys.exit(1)
    except requests.exceptions.RequestException as e:
        print(f"ERROR: Network error: {e}")
        sys.exit(1)

    # Remove detailed PR list from output (too verbose)
    output_metrics = {k: v for k, v in metrics.items() if k != "prs_analyzed"}
    # Also remove raw latency list
    output_metrics.pop("review_latencies_seconds", None)

    if args.output in ("json", "both"):
        print("\n" + "=" * 60)
        print("JSON Output:")
        print("=" * 60)
        print(json.dumps(output_metrics, indent=2))

    if args.output in ("markdown", "both"):
        print("\n" + "=" * 60)
        print("Markdown Output:")
        print("=" * 60)
        print(format_markdown(output_metrics))

    # Exit with non-zero if status is bad
    if metrics["status"] == "NEEDS ATTENTION":
        sys.exit(2)

    return 0


if __name__ == "__main__":
    sys.exit(main() or 0)
