"""
Event Normalizer - Unified Event Processing for Meta Agent

This module provides event normalization and processing logic that bridges
webhook events from external services to the Meta Agent execution system.

Issue: #1822 - 整合開發工具 (Integrate Development Tools)
Milestone: M5 - Meta Agent 優化

Flow:
    WebhookEvent → EventNormalizer → GoalParser → TaskPlanner → Executor
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

from .bot_protocol import (
    BaseWebhookHandler,
    WebhookConfig,
    WebhookEvent,
    WebhookEventType,
    WebhookResponse,
    WebhookSource,
)
from .handlers.github_handler import GitHubWebhookHandler
from .handlers.jira_handler import JiraWebhookHandler
from .handlers.linear_handler import LinearWebhookHandler
from .handlers.slack_handler import SlackWebhookHandler
from .comment_triage import CommentTriageAgent, CommentTriageResult

try:
    from ..utils.rate_limit import check_ai_reviewer_rate_limit, check_pr_updated_debounce
except ImportError:
    from utils.rate_limit import check_ai_reviewer_rate_limit, check_pr_updated_debounce

try:
    from common.config.settings import settings
except ImportError:
    settings = None

# Import shared constants to prevent drift between github_api.py and normalizer.py
# Issue: Self-Trigger Loop Prevention
try:
    from utils.constants import MORNINGAI_REVIEW_MARKER
except ImportError:
    from ..utils.constants import MORNINGAI_REVIEW_MARKER

logger = logging.getLogger(__name__)


def is_self_generated_review(event: "WebhookEvent") -> bool:
    """
    Check if a PR_REVIEWED event was generated by our own orchestrator.

    Issue: Self-Trigger Loop Prevention
    When the orchestrator posts a review to GitHub, GitHub sends a PR_REVIEWED
    webhook back. Without this check, the orchestrator would process its own
    review as a new event, creating an infinite feedback loop.

    The detection works by checking for a hidden HTML comment marker in the
    review body that the orchestrator adds when posting reviews.

    Args:
        event: The webhook event to check

    Returns:
        True if this is a self-generated review that should be skipped
    """
    # Only check PR_REVIEWED events
    if event.event_type != WebhookEventType.PR_REVIEWED:
        return False

    # Check the event description (review body) for our marker
    description = event.description or ""
    if MORNINGAI_REVIEW_MARKER in description:
        logger.info(
            "[EventNormalizer] Detected self-generated review, skipping to prevent feedback loop",
            extra={
                "operation": "self_review_detection",
                "event_id": event.event_id,
                "repo": f"{event.repo_owner}/{event.repo_name}",
                "pr_number": event.resource_id,
            }
        )
        return True

    # Also check raw payload for the marker (in case description is truncated)
    raw_payload = event.raw_payload or {}
    review = raw_payload.get("review", {})
    review_body = review.get("body", "")
    if MORNINGAI_REVIEW_MARKER in review_body:
        logger.info(
            "[EventNormalizer] Detected self-generated review (from raw payload), skipping",
            extra={
                "operation": "self_review_detection",
                "event_id": event.event_id,
                "repo": f"{event.repo_owner}/{event.repo_name}",
                "pr_number": event.resource_id,
            }
        )
        return True

    return False


def should_skip_orchestrator_pr_event(event: "WebhookEvent") -> bool:
    """
    Check if a PR event should be skipped because it's from an orchestrator-generated branch.

    Issue: Docs PR Noise Reduction
    When the orchestrator creates a docs PR (branch: orchestrator/*), GitHub sends
    PR webhooks back. Without this check, the orchestrator would process its own
    PR events and potentially create more docs PRs, causing noise.

    This is a zero-cost check that uses only the webhook payload data.

    Args:
        event: The webhook event to check

    Returns:
        True if this is an orchestrator-generated PR that should be skipped
    """
    # Only check PR-related events
    pr_event_types = {
        WebhookEventType.PR_OPENED,
        WebhookEventType.PR_CLOSED,
        WebhookEventType.PR_MERGED,
        WebhookEventType.PR_UPDATED,
        WebhookEventType.PR_REVIEWED,
    }
    if event.event_type not in pr_event_types:
        return False

    # Extract head branch from raw payload
    raw_payload = event.raw_payload or {}
    pr_data = raw_payload.get("pull_request", {})
    head_ref = pr_data.get("head", {}).get("ref", "")

    # Type guard: ensure head_ref is a string to prevent AttributeError
    # Malformed payloads might have None, int, dict, etc.
    if not isinstance(head_ref, str):
        head_ref = ""

    # Check if branch starts with orchestrator/ prefix
    if head_ref.startswith("orchestrator/"):
        repo = f"{event.repo_owner}/{event.repo_name}" if event.repo_owner and event.repo_name else "unknown"
        logger.info(
            "[EventNormalizer] Skipping orchestrator-generated PR event",
            extra={
                "operation": "orchestrator_pr_skip",
                "event_id": event.event_id,
                "repo": repo,
                "pr_number": event.resource_id,
                "head_ref": head_ref,
                "event_type": event.event_type.value,
                "reason": "orchestrator_branch_prefix",
            }
        )
        return True

    return False


def is_internal_repo_allowed(repo: str) -> bool:
    """
    Check if an internal repo is allowed for AI review in Staging.

    Phase B-B: Internal Repo Dogfooding
    This enables MorningAI to review its own code in Staging environment.

    Preconditions (all must be true):
    1. settings object is available
    2. allow_internal_repos_in_staging is True
    3. is_staging environment is True
    4. repo is in internal_repos_whitelist

    Args:
        repo: Repository in owner/repo format (e.g., 'RC918/morningai')

    Returns:
        True if the repo is an internal repo and dogfooding is enabled in Staging
    """
    if not settings:
        return False

    # Gather all preconditions using getattr for robustness
    is_staging_env = getattr(settings, 'is_staging', False)
    allow_internal = getattr(settings, 'allow_internal_repos_in_staging', False)
    whitelist_str = getattr(settings, 'internal_repos_whitelist', '')

    # Dogfooding is only allowed when all preconditions are met
    if not (allow_internal and is_staging_env and whitelist_str):
        return False

    # Parse whitelist and check if repo is allowed
    whitelist = {r.strip() for r in whitelist_str.split(',') if r.strip()}
    is_allowed = repo in whitelist

    if is_allowed:
        logger.info(
            "[EventNormalizer] Internal repo allowed for AI review (dogfooding)",
            extra={
                "operation": "internal_repo_dogfooding",
                "repo": repo,
                "is_staging": is_staging_env,
            }
        )

    return is_allowed


@dataclass
class PRUpdatedAllowedResult:
    """Result of PR_UPDATED allowed check"""
    is_allowed: bool
    reason: str
    should_schedule_job: bool = False
    job_token: Optional[str] = None
    debounce_seconds: int = 30


def is_pr_updated_allowed(repo: str, pr_number: int, redis_url: str = None) -> PRUpdatedAllowedResult:
    """
    Check if a PR_UPDATED event should trigger a delayed review job.

    Phase B-B: PR_UPDATED Event Support with Debounce/Throttle
    This enables AI review on PR updates (push events) with cost protection.

    CRITICAL FIX: Now returns should_schedule_job=True for first event,
    allowing caller to enqueue a delayed job that sleeps then processes.

    Preconditions (all must be true):
    1. settings.enable_pr_updated_review is True
    2. repo is in pr_updated_repos_whitelist (or whitelist is empty = all repos)
    3. Debounce check passes (first event or debounce window expired)
    4. Throttle check passes (not reviewed too recently)

    Args:
        repo: Repository in owner/repo format (e.g., 'RC918/morningai')
        pr_number: Pull request number
        redis_url: Optional Redis URL for debounce/throttle tracking

    Returns:
        PRUpdatedAllowedResult with:
        - is_allowed: True if event should trigger review workflow
        - should_schedule_job: True if caller should enqueue delayed job
        - job_token: Token to pass to delayed job for verification
        - debounce_seconds: Debounce window for delayed job sleep
        - reason: Human-readable explanation
    """
    if not settings:
        return PRUpdatedAllowedResult(
            is_allowed=False,
            reason="settings_unavailable",
        )

    enable_pr_updated = getattr(settings, 'enable_pr_updated_review', False)
    if not enable_pr_updated:
        return PRUpdatedAllowedResult(
            is_allowed=False,
            reason="pr_updated_review_disabled",
        )

    whitelist_str = getattr(settings, 'pr_updated_repos_whitelist', '')
    if whitelist_str:
        whitelist = {r.strip() for r in whitelist_str.split(',') if r.strip()}
        if repo not in whitelist:
            return PRUpdatedAllowedResult(
                is_allowed=False,
                reason="repo_not_in_whitelist",
            )

    debounce_seconds = getattr(settings, 'pr_updated_debounce_seconds', 30)
    throttle_seconds = getattr(settings, 'pr_updated_throttle_seconds', 600)

    debounce_result = check_pr_updated_debounce(
        repo=repo,
        pr_number=pr_number,
        debounce_seconds=debounce_seconds,
        throttle_seconds=throttle_seconds,
        redis_url=redis_url,
    )

    if debounce_result.should_schedule_job:
        logger.info(
            "[EventNormalizer] PR_UPDATED event - scheduling delayed job",
            extra={
                "operation": "pr_updated_schedule_job",
                "repo": repo,
                "pr_number": pr_number,
                "job_token": debounce_result.job_token,
                "debounce_seconds": debounce_seconds,
            }
        )
        return PRUpdatedAllowedResult(
            is_allowed=True,
            reason="first_event: delayed job scheduled",
            should_schedule_job=True,
            job_token=debounce_result.job_token,
            debounce_seconds=debounce_seconds,
        )

    logger.info(
        "[EventNormalizer] PR_UPDATED event debounced/throttled",
        extra={
            "operation": "pr_updated_debounce_check",
            "repo": repo,
            "pr_number": pr_number,
            "reason": debounce_result.reason,
        }
    )
    return PRUpdatedAllowedResult(
        is_allowed=False,
        reason=debounce_result.reason,
    )


@dataclass
class NormalizedTask:
    """
    A task extracted from a webhook event, ready for Meta Agent processing.

    This represents the bridge between external events and internal task execution.
    """
    task_id: str
    source_event: WebhookEvent
    goal_text: str
    priority: str
    requires_approval: bool
    context: Dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.now)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization"""
        return {
            "task_id": self.task_id,
            "source_event_id": self.source_event.event_id,
            "source": self.source_event.source.value,
            "event_type": self.source_event.event_type.value,
            "goal_text": self.goal_text,
            "priority": self.priority,
            "requires_approval": self.requires_approval,
            "context": self.context,
            "created_at": self.created_at.isoformat(),
        }


class EventNormalizer:
    """
    Normalizes webhook events from different sources into a unified format
    and prepares them for Meta Agent processing.

    This class:
    1. Routes events to appropriate handlers based on source
    2. Validates and normalizes event data
    3. Extracts actionable tasks from events
    4. Determines priority and approval requirements
    """

    # Event types that typically require human approval
    HIGH_RISK_EVENT_TYPES = {
        WebhookEventType.PR_MERGED,
        WebhookEventType.ISSUE_CLOSED,
        WebhookEventType.BRANCH_DELETED,
    }

    # Event types that are actionable (can trigger Meta Agent tasks)
    # P0: PR_COMMENTED removed to prevent self-trigger loop (CTO decision 2025-12-22)
    # MorningAI is a "one-way reviewer", not a "conversational chatbot"
    # See: EPIC B - GitHub App migration for future Identity Filter support
    ACTIONABLE_EVENT_TYPES = {
        WebhookEventType.ISSUE_CREATED,
        WebhookEventType.ISSUE_COMMENTED,
        WebhookEventType.ISSUE_ASSIGNED,
        WebhookEventType.PR_OPENED,
        WebhookEventType.PR_REVIEWED,
        # WebhookEventType.PR_COMMENTED,  # DISABLED: causes self-trigger loop
        WebhookEventType.MENTION_RECEIVED,
        WebhookEventType.COMMAND_RECEIVED,
    }

    # AI Reviewer standard phrases that indicate actionable feedback
    # Issue: #2209 - 修復 AI Reviewer 評論接收機制
    # Note: Removed overly generic keywords (refactor, simplify, optimize)
    # to avoid false positives from human comments
    AI_REVIEWER_KEYWORDS = [
        # Codex / Copilot standard phrases
        "suggestion:", "consider:", "recommend:", "could be improved",
        "potential issue", "possible bug", "code smell",
        # Gemini Code Assist standard phrases
        "code review", "improvement suggestion", "best practice",
        "security concern", "performance issue", "maintainability",
        # CodeRabbit standard phrases
        "actionable comment", "nitpick:", "issue:",
        # General AI reviewer phrases (specific, not generic)
        "fix:", "bug:", "vulnerability", "deprecated", "unused", "dead code",
    ]

    # Priority mapping based on labels
    PRIORITY_LABELS = {
        "critical": ["critical", "urgent", "p0", "blocker", "緊急"],
        "high": ["high", "important", "p1", "高優先"],
        "medium": ["medium", "normal", "p2", "中優先"],
        "low": ["low", "minor", "p3", "低優先"],
    }

    def __init__(
        self,
        github_config: Optional[WebhookConfig] = None,
        jira_config: Optional[WebhookConfig] = None,
        linear_config: Optional[WebhookConfig] = None,
        slack_config: Optional[WebhookConfig] = None,
    ):
        """
        Initialize the EventNormalizer with handler configurations.

        Args:
            github_config: Configuration for GitHub webhook handler
            jira_config: Configuration for Jira webhook handler
            linear_config: Configuration for Linear webhook handler
            slack_config: Configuration for Slack webhook handler
        """
        self.handlers: Dict[WebhookSource, BaseWebhookHandler] = {
            WebhookSource.GITHUB: GitHubWebhookHandler(github_config),
            WebhookSource.JIRA: JiraWebhookHandler(jira_config),
            WebhookSource.LINEAR: LinearWebhookHandler(linear_config),
            WebhookSource.SLACK: SlackWebhookHandler(slack_config),
        }

        # Initialize Comment Triage Agent for AI reviewer comment classification
        # Issue: #2210 - Comment Triage Agent 設計與實作
        self.comment_triage_agent = CommentTriageAgent()

        logger.info(
            "[EventNormalizer] Initialized with handlers: %s",
            list(self.handlers.keys()),
        )

    def get_handler(self, source: WebhookSource) -> Optional[BaseWebhookHandler]:
        """
        Get the handler for a specific webhook source.

        Args:
            source: Webhook source

        Returns:
            Handler instance or None if not configured
        """
        return self.handlers.get(source)

    def process_webhook(
        self,
        source: WebhookSource,
        headers: Dict[str, str],
        payload: bytes,
        parsed_payload: Dict[str, Any],
    ) -> WebhookResponse:
        """
        Process a webhook request from any supported source.

        Args:
            source: Webhook source (github, jira, slack)
            headers: Request headers
            payload: Raw request body
            parsed_payload: Parsed JSON payload

        Returns:
            WebhookResponse with processing result
        """
        handler = self.get_handler(source)
        if not handler:
            logger.warning("[EventNormalizer] No handler for source: %s", source)
            return WebhookResponse(
                success=False,
                message=f"Unsupported webhook source: {source.value}",
                errors=[f"No handler configured for {source.value}"],
            )

        return handler.handle(headers, payload, parsed_payload)

    def parse_event(
        self,
        source: WebhookSource,
        headers: Dict[str, str],
        payload: Dict[str, Any],
    ) -> Optional[WebhookEvent]:
        """
        Parse a webhook payload into a normalized WebhookEvent.

        Args:
            source: Webhook source
            headers: Request headers
            payload: Parsed JSON payload

        Returns:
            Normalized WebhookEvent or None if parsing fails
        """
        handler = self.get_handler(source)
        if not handler:
            logger.warning("[EventNormalizer] No handler for source: %s", source)
            return None

        try:
            return handler.parse_event(headers, payload)
        except Exception as e:
            logger.exception(
                "[EventNormalizer] Failed to parse event from %s: %s",
                source.value,
                e,
            )
            return None

    def is_actionable(self, event: WebhookEvent) -> bool:
        """
        Determine if an event is actionable (should trigger Meta Agent).

        Args:
            event: Normalized webhook event

        Returns:
            True if event should trigger task creation

        Issue: #2209 - 修復 AI Reviewer 評論接收機制
        Issue: #2254 - is_actionable observability
        Phase B-B: Internal Repo Dogfooding support
        Issue: Self-Trigger Loop Prevention
        """
        # P1: Self-Review Detection - Skip our own reviews to prevent feedback loop
        # Issue: Self-Trigger Loop Prevention
        # When the orchestrator posts a review, GitHub sends a PR_REVIEWED webhook.
        # Without this check, we would process our own review and create an infinite loop.
        if is_self_generated_review(event):
            return False

        # P2: Orchestrator Branch Detection - Skip PRs from orchestrator/* branches
        # Issue: Docs PR Noise Reduction
        # When the orchestrator creates a docs PR, GitHub sends PR webhooks back.
        # Without this check, we would process our own PRs and create more noise.
        if should_skip_orchestrator_pr_event(event):
            return False

        # P0: Disable PR_COMMENTED events entirely (CTO decision 2025-12-22)
        # This is a hard block that cannot be bypassed by is_ai_reviewer or other logic.
        # MorningAI is a "one-way reviewer", not a "conversational chatbot".
        # Without this, inline review comments trigger webhooks that cause infinite loops.
        # See: EPIC B - GitHub App migration for future Identity Filter support
        if event.event_type == WebhookEventType.PR_COMMENTED:
            repo = f"{event.repo_owner}/{event.repo_name}" if event.repo_owner and event.repo_name else "unknown"
            logger.debug(
                "[EventNormalizer] PR_COMMENTED event skipped (conversational review disabled)",
                extra={
                    "operation": "pr_commented_disabled",
                    "event_id": event.event_id,
                    "repo": repo,
                    "pr_number": event.resource_id or "unknown",
                    "actor": event.actor_name,
                    "reason": "no_conversational_review",
                }
            )
            return False

        is_ai_reviewer = bool(event.metadata.get("is_ai_reviewer"))
        bot_name = event.metadata.get("review_source", "unknown") if is_ai_reviewer else None
        repo = f"{event.repo_owner}/{event.repo_name}" if event.repo_owner and event.repo_name else "unknown"
        pr_number = event.resource_id or "unknown"
        matched_keywords: List[str] = []
        is_actionable_result = False
        actionable_reason = ""
        is_internal_repo = is_internal_repo_allowed(repo)

        # Check if event type is in actionable list
        if event.event_type in self.ACTIONABLE_EVENT_TYPES:
            is_actionable_result = True
            actionable_reason = "event_type_actionable"

        # Phase B-B: Check if PR_UPDATED event is allowed (with debounce/throttle)
        # PR_UPDATED is NOT in ACTIONABLE_EVENT_TYPES by default to prevent cost explosion
        # It requires explicit enablement via settings and passes debounce/throttle checks
        elif event.event_type == WebhookEventType.PR_UPDATED:
            try:
                pr_number_int = int(pr_number) if pr_number != "unknown" else 0
            except (ValueError, TypeError):
                pr_number_int = 0

            if pr_number_int > 0:
                pr_updated_result = is_pr_updated_allowed(
                    repo=repo,
                    pr_number=pr_number_int,
                )
                if pr_updated_result.is_allowed:
                    is_actionable_result = True
                    actionable_reason = f"pr_updated_allowed:{pr_updated_result.reason}"
                    event.metadata["pr_updated_should_schedule_job"] = pr_updated_result.should_schedule_job
                    event.metadata["pr_updated_job_token"] = pr_updated_result.job_token
                    event.metadata["pr_updated_debounce_seconds"] = pr_updated_result.debounce_seconds
                    logger.info(
                        "[EventNormalizer] PR_UPDATED event is actionable",
                        extra={
                            "operation": "pr_updated_actionable",
                            "event_id": event.event_id,
                            "repo": repo,
                            "pr_number": pr_number,
                            "should_schedule_job": pr_updated_result.should_schedule_job,
                            "job_token": pr_updated_result.job_token,
                        }
                    )
                else:
                    logger.debug(
                        "[EventNormalizer] PR_UPDATED event not actionable: %s",
                        pr_updated_result.reason,
                        extra={
                            "operation": "pr_updated_not_actionable",
                            "event_id": event.event_id,
                            "repo": repo,
                            "pr_number": pr_number,
                            "reason": pr_updated_result.reason,
                        }
                    )

        # Check if event is from an AI reviewer (always actionable)
        # Issue: #2209 - AI reviewer events should be processed
        elif is_ai_reviewer:
            is_actionable_result = True
            actionable_reason = "ai_reviewer_event"

        else:
            # Check for specific keywords in title/description
            text = f"{event.title or ''} {event.description or ''}".lower()
            action_keywords = [
                "fix", "implement", "add", "create", "update", "refactor",
                "修復", "實現", "新增", "建立", "更新", "重構",
                "@bot", "@agent", "@meta-agent",
            ]

            for keyword in action_keywords:
                if keyword in text:
                    matched_keywords.append(keyword)
                    is_actionable_result = True
                    actionable_reason = "action_keyword_match"
                    break

            # Check for AI reviewer standard phrases
            # Issue: #2209 - Recognize AI reviewer standard terminology
            if not is_actionable_result:
                for keyword in self.AI_REVIEWER_KEYWORDS:
                    if keyword in text:
                        matched_keywords.append(keyword)
                        is_actionable_result = True
                        actionable_reason = "ai_reviewer_keyword_match"
                        logger.debug(
                            "[EventNormalizer] AI reviewer keyword detected: %s",
                            keyword,
                        )
                        break

        # Issue: #2254 - Structured logging for is_actionable observability
        # Log all AI reviewer comment processing for false positive monitoring
        if is_ai_reviewer:
            logger.info(
                "[EventNormalizer] AI reviewer comment processed",
                extra={
                    "operation": "ai_reviewer_is_actionable",
                    "event_id": event.event_id,
                    "is_actionable": is_actionable_result,
                    "bot_name": bot_name,
                    "repo": repo,
                    "pr_number": pr_number,
                    "matched_keywords": matched_keywords,
                    "actionable_reason": actionable_reason,
                    "is_internal_repo": is_internal_repo,
                }
            )

        # Phase B-B: Log internal repo events for dogfooding observability
        if is_internal_repo:
            logger.info(
                "[EventNormalizer] Internal repo event processed (dogfooding)",
                extra={
                    "operation": "internal_repo_event",
                    "event_id": event.event_id,
                    "is_actionable": is_actionable_result,
                    "repo": repo,
                    "pr_number": pr_number,
                    "event_type": event.event_type.value,
                    "actionable_reason": actionable_reason,
                }
            )

        return is_actionable_result

    def extract_task(self, event: WebhookEvent) -> Optional[NormalizedTask]:
        """
        Extract an actionable task from a webhook event.

        Args:
            event: Normalized webhook event

        Returns:
            NormalizedTask ready for Meta Agent, or None if not actionable
        """
        if not self.is_actionable(event):
            logger.debug(
                "[EventNormalizer] Event %s is not actionable",
                event.event_id,
            )
            return None

        # Generate goal text from event
        goal_text = event.to_goal_text()

        # Determine priority
        priority = self._determine_priority(event)

        # Determine if approval is required
        requires_approval = self._requires_approval(event)

        # Build context for Meta Agent
        context = self._build_context(event)

        # Generate task ID with full UUID for DB compatibility
        # Format: webhook-{source}-{full_uuid}
        # The db_writer.normalize_and_validate_uuid() will extract the UUID portion
        import uuid
        task_uuid = str(uuid.uuid4())
        task_id = f"webhook-{event.source.value}-{task_uuid}"

        task = NormalizedTask(
            task_id=task_id,
            source_event=event,
            goal_text=goal_text,
            priority=priority,
            requires_approval=requires_approval,
            context=context,
        )

        logger.info(
            "[EventNormalizer] Extracted task: id=%s, priority=%s, approval=%s",
            task_id,
            priority,
            requires_approval,
        )

        return task

    def _determine_priority(self, event: WebhookEvent) -> str:
        """
        Determine task priority from event labels and content.

        Args:
            event: Normalized webhook event

        Returns:
            Priority string (critical, high, medium, low)
        """
        # Check event priority field first
        if event.priority:
            return event.priority

        # Check labels
        labels_lower = [label.lower() for label in event.labels]
        for priority, keywords in self.PRIORITY_LABELS.items():
            for keyword in keywords:
                if keyword in labels_lower:
                    return priority

        # Check title/description for priority keywords
        text = f"{event.title or ''} {event.description or ''}".lower()
        for priority, keywords in self.PRIORITY_LABELS.items():
            for keyword in keywords:
                if keyword in text:
                    return priority

        # Default to medium
        return "medium"

    def _requires_approval(self, event: WebhookEvent) -> bool:
        """
        Determine if task requires human approval.

        Args:
            event: Normalized webhook event

        Returns:
            True if approval is required
        """
        # High-risk event types always require approval
        if event.event_type in self.HIGH_RISK_EVENT_TYPES:
            return True

        # Check for high-risk keywords
        text = f"{event.title or ''} {event.description or ''}".lower()
        high_risk_keywords = [
            "production", "deploy", "delete", "remove", "drop",
            "生產", "部署", "刪除", "移除",
            "security", "credential", "secret", "password",
            "安全", "憑證", "密碼",
        ]

        for keyword in high_risk_keywords:
            if keyword in text:
                return True

        return False

    def _build_context(self, event: WebhookEvent) -> Dict[str, Any]:
        """
        Build context dictionary for Meta Agent.

        Args:
            event: Normalized webhook event

        Returns:
            Context dictionary with relevant information
        """
        context = {
            "source": event.source.value,
            "event_type": event.event_type.value,
            "event_id": event.event_id,
            "url": event.url,
            "actor": event.actor_name,
        }

        # Add repository context
        if event.repo_owner and event.repo_name:
            context["repo"] = f"{event.repo_owner}/{event.repo_name}"

        # Add project context (for Jira)
        if event.project_key:
            context["project"] = event.project_key

        # Add resource context
        # Fix: Decouple resource_type from resource_id - they should be added independently
        # Previously, resource_type was only added if resource_id was truthy, causing
        # resource_type to be missing when resource_id was empty string or None
        if event.resource_type:
            context["resource_type"] = event.resource_type
        if event.resource_id:
            context["resource_id"] = event.resource_id

        # Add labels and assignees
        if event.labels:
            context["labels"] = event.labels
        if event.assignees:
            context["assignees"] = event.assignees

        # Phase B-B: Pass PR_UPDATED debounce metadata to task context
        # This enables the webhook handler to enqueue delayed jobs
        if event.metadata.get("pr_updated_should_schedule_job"):
            context["pr_updated_should_schedule_job"] = event.metadata["pr_updated_should_schedule_job"]
            context["pr_updated_job_token"] = event.metadata.get("pr_updated_job_token")
            context["pr_updated_debounce_seconds"] = event.metadata.get("pr_updated_debounce_seconds")

        return context

    def batch_process(
        self,
        events: List[WebhookEvent],
    ) -> List[NormalizedTask]:
        """
        Process multiple events and extract actionable tasks.

        Args:
            events: List of normalized webhook events

        Returns:
            List of extracted tasks
        """
        tasks = []
        for event in events:
            task = self.extract_task(event)
            if task:
                tasks.append(task)

        logger.info(
            "[EventNormalizer] Batch processed %d events, extracted %d tasks",
            len(events),
            len(tasks),
        )

        return tasks

    def triage_comment(
        self, event: WebhookEvent, redis_url: Optional[str] = None
    ) -> Optional[CommentTriageResult]:
        """
        Triage an AI reviewer comment event with rate limiting.

        This method first checks rate limits, then delegates to the
        CommentTriageAgent to classify the comment, assess risk, and
        determine if it should be auto-fixed.

        Args:
            event: WebhookEvent with is_ai_reviewer=True in metadata
            redis_url: Optional Redis URL for rate limiting

        Returns:
            CommentTriageResult with classification and recommendations,
            or None if the event is not from an AI reviewer or rate limited

        Issue: #2210 - Comment Triage Agent 設計與實作
        Issue: #2253 - AI Reviewer Rate Limiting
        """
        is_ai_reviewer = bool(event.metadata.get("is_ai_reviewer"))

        if is_ai_reviewer:
            repo = f"{event.repo_owner}/{event.repo_name}" if event.repo_owner and event.repo_name else "unknown"
            pr_id = f"{repo}#{event.resource_id}" if event.resource_id else f"{repo}#unknown"
            bot_name = event.metadata.get("review_source", "unknown")

            rate_limit_result = check_ai_reviewer_rate_limit(
                pr_id=pr_id,
                repo=repo,
                bot_name=bot_name,
                redis_url=redis_url,
            )

            if not rate_limit_result.allowed:
                logger.warning(
                    "[EventNormalizer] AI reviewer comment rate limited",
                    extra={
                        "operation": "ai_reviewer_rate_limited",
                        "event_id": event.event_id,
                        "pr_id": pr_id,
                        "repo": repo,
                        "bot_name": bot_name,
                        "exceeded_dimension": rate_limit_result.exceeded_dimension,
                        "current_count": rate_limit_result.current_count,
                        "limit": rate_limit_result.limit,
                    }
                )
                return None

        return self.comment_triage_agent.triage(event)

    def batch_triage_comments(
        self, events: List[WebhookEvent], redis_url: Optional[str] = None
    ) -> List[CommentTriageResult]:
        """
        Triage multiple AI reviewer comment events with rate limiting.

        Args:
            events: List of WebhookEvents
            redis_url: Optional Redis URL for rate limiting

        Returns:
            List of CommentTriageResults for AI reviewer events (rate limited events excluded)

        Issue: #2210 - Comment Triage Agent 設計與實作
        Issue: #2253 - AI Reviewer Rate Limiting
        """
        results = []
        for event in events:
            result = self.triage_comment(event, redis_url=redis_url)
            if result:
                results.append(result)
        return results
