"""
Event Normalizer - Unified Event Processing for Meta Agent

This module provides event normalization and processing logic that bridges
webhook events from external services to the Meta Agent execution system.

Issue: #1822 - 整合開發工具 (Integrate Development Tools)
Milestone: M5 - Meta Agent 優化

Flow:
    WebhookEvent → EventNormalizer → GoalParser → TaskPlanner → Executor
"""

import logging
import time
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

from .bot_protocol import (
    BaseWebhookHandler,
    WebhookConfig,
    WebhookEvent,
    WebhookEventType,
    WebhookResponse,
    WebhookSource,
)
from .handlers.github_handler import GitHubWebhookHandler
from .handlers.jira_handler import JiraWebhookHandler
from .handlers.linear_handler import LinearWebhookHandler
from .handlers.slack_handler import SlackWebhookHandler
from .comment_triage import CommentTriageAgent, CommentTriageResult
from .command_router import CommandRouter, CommandTrigger

try:
    from ..utils.rate_limit import check_ai_reviewer_rate_limit, check_pr_updated_debounce
except ImportError:
    from utils.rate_limit import check_ai_reviewer_rate_limit, check_pr_updated_debounce

try:
    from common.config.settings import settings
except ImportError:
    settings = None

# Import shared constants to prevent drift between github_api.py and normalizer.py
# Issue: Self-Trigger Loop Prevention
try:
    from utils.constants import MORNINGAI_REVIEW_MARKER
except ImportError:
    from ..utils.constants import MORNINGAI_REVIEW_MARKER

logger = logging.getLogger(__name__)


def is_self_generated_review(event: "WebhookEvent") -> bool:
    """
    Check if a PR_REVIEWED event was generated by our own orchestrator.

    Issue: Self-Trigger Loop Prevention
    When the orchestrator posts a review to GitHub, GitHub sends a PR_REVIEWED
    webhook back. Without this check, the orchestrator would process its own
    review as a new event, creating an infinite feedback loop.

    The detection works by checking for a hidden HTML comment marker in the
    review body that the orchestrator adds when posting reviews.

    Args:
        event: The webhook event to check

    Returns:
        True if this is a self-generated review that should be skipped
    """
    # Only check PR_REVIEWED events
    if event.event_type != WebhookEventType.PR_REVIEWED:
        return False

    # Check the event description (review body) for our marker
    description = event.description or ""
    if MORNINGAI_REVIEW_MARKER in description:
        logger.info(
            "[EventNormalizer] Detected self-generated review, skipping to prevent feedback loop",
            extra={
                "operation": "self_review_detection",
                "event_id": event.event_id,
                "repo": f"{event.repo_owner}/{event.repo_name}",
                "pr_number": event.resource_id,
            }
        )
        return True

    # Also check raw payload for the marker (in case description is truncated)
    raw_payload = event.raw_payload or {}
    review = raw_payload.get("review", {})
    review_body = review.get("body", "")
    if MORNINGAI_REVIEW_MARKER in review_body:
        logger.info(
            "[EventNormalizer] Detected self-generated review (from raw payload), skipping",
            extra={
                "operation": "self_review_detection",
                "event_id": event.event_id,
                "repo": f"{event.repo_owner}/{event.repo_name}",
                "pr_number": event.resource_id,
            }
        )
        return True

    return False


def _extract_head_branch_from_payload(raw_payload: dict) -> str:
    """
    Extract head branch from various GitHub webhook payload structures.

    Issue: Staging Observation (#3047) - Consolidated branch extraction
    This helper unifies branch extraction logic used in multiple places:
    - should_skip_orchestrator_pr_event() for orchestrator branch detection
    - is_actionable() UNKNOWN event logging for staging observation

    Supported payload structures:
    - PR events: pull_request.head.ref
    - Check suite events: check_suite.head_branch or check_suite.pull_requests[0].head.ref
    - Check run events: check_run.check_suite.head_branch
    - Status events: branches[0].name

    Args:
        raw_payload: The raw webhook payload dict

    Returns:
        The head branch name, or empty string if not found
    """
    if not isinstance(raw_payload, dict):
        return ""

    head_ref = ""

    # Try PR payload first (most common for PR events)
    pr_data = raw_payload.get("pull_request", {})
    if pr_data and isinstance(pr_data, dict):
        head_data = pr_data.get("head", {})
        if isinstance(head_data, dict):
            head_ref = head_data.get("ref", "")

    # Try check_suite payload (CI events)
    if not head_ref:
        check_suite = raw_payload.get("check_suite", {})
        if check_suite and isinstance(check_suite, dict):
            head_ref = check_suite.get("head_branch", "")
            # Also check pull_requests array in check_suite
            if not head_ref:
                prs = check_suite.get("pull_requests", [])
                if prs and isinstance(prs, list) and len(prs) > 0:
                    first_pr = prs[0]
                    if isinstance(first_pr, dict):
                        head_data = first_pr.get("head", {})
                        if isinstance(head_data, dict):
                            head_ref = head_data.get("ref", "")

    # Try check_run payload (CI events)
    if not head_ref:
        check_run = raw_payload.get("check_run", {})
        if check_run and isinstance(check_run, dict):
            check_suite_in_run = check_run.get("check_suite", {})
            if isinstance(check_suite_in_run, dict):
                head_ref = check_suite_in_run.get("head_branch", "")

    # Try status event payload
    if not head_ref:
        branches = raw_payload.get("branches", [])
        if branches and isinstance(branches, list) and len(branches) > 0:
            first_branch = branches[0]
            if isinstance(first_branch, dict):
                head_ref = first_branch.get("name", "")

    # Ensure we return a string
    if not isinstance(head_ref, str):
        head_ref = ""

    return head_ref


def should_skip_orchestrator_pr_event(event: "WebhookEvent") -> bool:
    """
    Check if a PR event should be skipped because it's from an orchestrator-generated PR.

    Issue: Self-Trigger Loop Prevention (Dec 2025)
    Issue: Garbage PR Fix - Defense in Depth (Dec 2025)

    When the orchestrator creates a docs PR, GitHub sends PR webhooks back.
    Without this check, the orchestrator would process its own PR events and
    create more docs PRs, causing an infinite self-trigger loop.

    Detection methods (any match triggers skip):
    1. Branch prefix: orchestrator/* branches
    2. Label filter: PRs with 'orchestrator-docs' or 'orchestrator-docs-test' labels

    Defense in Depth (Dec 2025):
    This function also checks UNKNOWN events, which may be CI events (check_suite,
    check_run, status) that reference orchestrator PRs. Combined with the UNKNOWN
    event filter in is_actionable(), this provides layered protection.

    This is a zero-cost check that uses only the webhook payload data.

    Args:
        event: The webhook event to check

    Returns:
        True if this is an orchestrator-generated PR that should be skipped
    """
    # Only check PR-related events and UNKNOWN events (which may be CI events)
    # Issue: Garbage PR Fix - UNKNOWN events can be check_suite/check_run/status
    # that reference orchestrator PRs and should be filtered
    pr_event_types = {
        WebhookEventType.PR_OPENED,
        WebhookEventType.PR_CLOSED,
        WebhookEventType.PR_MERGED,
        WebhookEventType.PR_UPDATED,
        WebhookEventType.PR_REVIEWED,
        WebhookEventType.UNKNOWN,  # CI events parsed as UNKNOWN
    }
    if event.event_type not in pr_event_types:
        return False

    repo = f"{event.repo_owner}/{event.repo_name}" if event.repo_owner and event.repo_name else "unknown"

    # Extract head branch using consolidated helper function
    # See _extract_head_branch_from_payload() for supported payload structures
    raw_payload = event.raw_payload or {}
    head_ref = _extract_head_branch_from_payload(raw_payload)

    # Check 1: Label filter - skip PRs with orchestrator-docs labels
    # This catches PRs created by any actor (including Devin) that have the orchestrator label
    # Import constants from utils/constants.py to ensure single source of truth
    from utils.constants import LABEL_ORCHESTRATOR_DOCS, LABEL_ORCHESTRATOR_DOCS_TEST
    orchestrator_labels = {LABEL_ORCHESTRATOR_DOCS.lower(), LABEL_ORCHESTRATOR_DOCS_TEST.lower()}

    # Type guard: filter out non-string labels to prevent AttributeError on .lower()
    # GitHub handler may produce None values if label.get("name") returns None
    event_labels_raw = event.labels if isinstance(event.labels, list) else []
    event_labels = set()
    for label in event_labels_raw:
        if isinstance(label, str):
            event_labels.add(label.lower())
        else:
            # Log warning for unexpected label type
            logger.warning(
                "[EventNormalizer] Unexpected label type in event",
                extra={
                    "operation": "label_type_warning",
                    "event_id": event.event_id,
                    "label_type": type(label).__name__,
                    "label_value": str(label)[:100],
                }
            )

    matched_labels = orchestrator_labels & event_labels

    # Staging observation (#3047) - capture GitHub event metadata for log analysis
    metadata = event.metadata or {}
    github_event = metadata.get("github_event", "unknown")
    github_action = metadata.get("action", "unknown")

    if matched_labels:
        logger.info(
            "[EventNormalizer] Skipping orchestrator-generated event (label match)",
            extra={
                "operation": "orchestrator_event_skip",
                "event_id": event.event_id,
                "repo": repo,
                "resource_id": event.resource_id,
                "head_ref": head_ref,
                "matched_labels": list(matched_labels),
                "event_type": event.event_type.value,
                "github_event": github_event,
                "github_action": github_action,
                "actor": event.actor_name or "unknown",
                "reason": "orchestrator_label_match",
            }
        )
        return True

    # Check 2: Branch prefix - skip events from orchestrator/* branches
    # This catches PR events, CI events (check_suite, check_run), and status events
    if head_ref.startswith("orchestrator/"):
        logger.info(
            "[EventNormalizer] Skipping orchestrator-generated event (branch match)",
            extra={
                "operation": "orchestrator_event_skip",
                "event_id": event.event_id,
                "repo": repo,
                "resource_id": event.resource_id,
                "head_ref": head_ref,
                "event_type": event.event_type.value,
                "github_event": github_event,
                "github_action": github_action,
                "actor": event.actor_name or "unknown",
                "reason": "orchestrator_branch_prefix",
            }
        )
        return True

    return False


# =============================================================================
# Smart PR Filtering - Trigger Threshold Layer (Dec 2025)
# =============================================================================
# These filters determine if a PR event is "worth documenting" based on:
# 1. Semantic title prefix (chore/ci/test/docs/style = skip)
# 2. File path patterns (config/docs/tests/CI only = skip)
#
# This is separate from the "orchestrator self-loop prevention" layer above.
# The goal is to reduce noise by only generating docs PRs for meaningful changes.
# =============================================================================

# Title prefixes that indicate non-actionable changes (skip docs generation)
# Only feat:, fix:, refactor: should trigger docs PR creation
SKIP_TITLE_PREFIXES = (
    "chore:",
    "chore(",
    "ci:",
    "ci(",
    "test:",
    "test(",
    "tests:",
    "tests(",
    "docs:",
    "docs(",
    "style:",
    "style(",
    "build:",
    "build(",
)

# File path patterns that indicate non-code changes
# If a PR ONLY modifies these patterns, skip docs generation
SKIP_FILE_PATTERNS = {
    # Config files
    "extensions": {".yaml", ".yml", ".json", ".toml", ".ini", ".cfg", ".conf"},
    # Documentation files
    "doc_extensions": {".md", ".rst", ".txt"},
    # Specific paths/prefixes
    "path_prefixes": (
        "docs/",
        ".github/",
        "tests/",
        "test/",
        "__tests__/",
    ),
    # Specific filenames
    "filenames": {
        "license",
        "license.md",
        "license.txt",
        "readme.md",
        "readme",
        "changelog.md",
        "changelog",
        "contributing.md",
        "requirements.txt",
        "requirements-dev.txt",
        "package-lock.json",
        "yarn.lock",
        "poetry.lock",
        "pipfile.lock",
        ".gitignore",
        ".gitattributes",
        ".editorconfig",
        ".prettierrc",
        ".eslintrc",
        ".flake8",
        "pyproject.toml",
        "setup.cfg",
        # NOTE: setup.py intentionally NOT included - it can contain significant
        # executable logic (custom build commands, entry points, etc.)
        "makefile",
        "dockerfile",
        "docker-compose.yml",
        "docker-compose.yaml",
        ".dockerignore",
        "render.yaml",
        ".env.example",
        ".env.sample",
    },
    # Test file patterns (suffix matching)
    "test_suffixes": ("_test.py", ".test.py", ".spec.ts", ".spec.js", ".test.ts", ".test.js"),
}


def _title_is_non_actionable(title: str) -> bool:
    """
    Check if a PR title indicates non-actionable changes.

    Smart PR Filtering (Dec 2025)
    PRs with titles starting with chore/ci/test/docs/style are considered
    non-actionable for docs generation purposes.

    Args:
        title: The PR title string

    Returns:
        True if the title indicates non-actionable changes (should skip)
    """
    if not title:
        return False

    title_lower = title.lower().strip()
    return title_lower.startswith(SKIP_TITLE_PREFIXES)


def _path_is_non_code(path: str) -> bool:
    """
    Check if a file path is a non-code file (config/docs/tests/CI).

    Smart PR Filtering (Dec 2025)
    Files matching these patterns are considered non-code changes.

    Args:
        path: The file path string

    Returns:
        True if the path is a non-code file
    """
    if not path:
        return True  # Empty/invalid path treated as non-code for safety (fail-open)

    # Normalize path separators for cross-platform robustness
    # GitHub API always uses forward slashes, but this makes the helper reusable
    path_lower = path.lower().replace("\\", "/")
    filename = path_lower.split("/")[-1]

    # Check exact filename matches
    if filename in SKIP_FILE_PATTERNS["filenames"]:
        return True

    # Check file extension
    ext = ""
    if "." in filename:
        ext = "." + filename.rsplit(".", 1)[-1]
    if ext in SKIP_FILE_PATTERNS["extensions"]:
        return True
    if ext in SKIP_FILE_PATTERNS["doc_extensions"]:
        return True

    # Check path prefixes
    for prefix in SKIP_FILE_PATTERNS["path_prefixes"]:
        if path_lower.startswith(prefix):
            return True

    # Check test file suffixes
    for suffix in SKIP_FILE_PATTERNS["test_suffixes"]:
        if path_lower.endswith(suffix):
            return True

    return False


def _should_skip_by_paths(file_paths: list) -> tuple:
    """
    Check if all changed files are non-code files.

    Smart PR Filtering (Dec 2025)
    If a PR ONLY modifies config/docs/tests/CI files, skip docs generation.

    Args:
        file_paths: List of changed file paths

    Returns:
        Tuple of (should_skip: bool, reason: str, sample_paths: list)
    """
    if not file_paths:
        # No files = skip (nothing to document)
        return True, "no_files", []

    non_code_paths = []
    code_paths = []

    for path in file_paths:
        if _path_is_non_code(path):
            non_code_paths.append(path)
        else:
            code_paths.append(path)
            # Early exit: found a code file, no need to check more
            if len(code_paths) >= 1:
                return False, "has_code_files", code_paths[:3]

    # All files are non-code
    return True, "only_non_code_files", non_code_paths[:5]


def _get_pr_files_from_api(repo: str, pr_number: int) -> tuple:
    """
    Fetch PR changed files from GitHub API.

    Smart PR Filtering (Dec 2025)
    This function fetches the list of changed files for a PR.
    It handles pagination and rate limiting gracefully.

    Args:
        repo: Repository in owner/repo format
        pr_number: Pull request number

    Returns:
        Tuple of (file_paths: list, error: str or None)
    """
    try:
        from tools.github_api import get_repo
        github_repo = get_repo()
        if not github_repo:
            return [], "repo_not_available"

        pr = github_repo.get_pull(pr_number)
        # get_files() returns a paginated list, iterate to get all
        file_paths = []
        for f in pr.get_files():
            file_paths.append(f.filename)
            # Early exit optimization: if we find a code file, we can stop
            # Return all files seen so far for debugging context
            if not _path_is_non_code(f.filename):
                return file_paths, None
        return file_paths, None
    except Exception as e:
        logger.warning(
            "[SmartFilter] Failed to fetch PR files from API",
            extra={
                "operation": "smart_filter_api_error",
                "repo": repo,
                "pr_number": pr_number,
                "error": str(e)[:200],
            }
        )
        return [], f"api_error: {str(e)[:100]}"


def should_skip_pr_by_smart_filters(event: "WebhookEvent") -> tuple:
    """
    Check if a PR event should be skipped based on smart filtering rules.

    Smart PR Filtering (Dec 2025)
    This function applies content-based and semantic filtering to determine
    if a PR is "worth documenting". It's separate from the orchestrator
    self-loop prevention layer.

    Filter Pipeline:
    1. Semantic title filter (cheap, runs first)
    2. File path filter (requires API call, runs only if title passes)

    Args:
        event: The webhook event to check

    Returns:
        Tuple of (should_skip: bool, reason: str, details: dict)
    """
    # Only apply to PR events
    pr_event_types = {
        WebhookEventType.PR_OPENED,
        WebhookEventType.PR_MERGED,
    }
    if event.event_type not in pr_event_types:
        return False, "not_pr_event", {}

    repo = f"{event.repo_owner}/{event.repo_name}" if event.repo_owner and event.repo_name else "unknown"
    pr_number = event.resource_id
    title = event.title or ""

    # Filter 1: Semantic title filter (cheap, runs first)
    if _title_is_non_actionable(title):
        logger.info(
            "[SmartFilter] Skipping PR by semantic title filter",
            extra={
                "operation": "pr_event_skip_semantic_title",
                "event_id": event.event_id,
                "repo": repo,
                "pr_number": pr_number,
                "title": title[:100],
                "reason": "non_actionable_title_prefix",
            }
        )
        return True, "semantic_title_skip", {"title_prefix": title.split(":")[0] if ":" in title else title[:20]}

    # Filter 2: File path filter (requires API call)
    # Only fetch files if title didn't trigger skip
    try:
        pr_number_int = int(pr_number) if pr_number else 0
    except (ValueError, TypeError):
        pr_number_int = 0

    if pr_number_int > 0:
        file_paths, api_error = _get_pr_files_from_api(repo, pr_number_int)

        if api_error:
            # API error: fail open (don't skip, let the PR be processed)
            logger.warning(
                "[SmartFilter] API error fetching PR files, failing open",
                extra={
                    "operation": "smart_filter_api_fail_open",
                    "event_id": event.event_id,
                    "repo": repo,
                    "pr_number": pr_number_int,
                    "error": api_error,
                }
            )
            return False, "api_error_fail_open", {"error": api_error}

        should_skip, reason, sample_paths = _should_skip_by_paths(file_paths)

        if should_skip:
            logger.info(
                "[SmartFilter] Skipping PR by file path filter",
                extra={
                    "operation": "pr_event_skip_file_paths_only",
                    "event_id": event.event_id,
                    "repo": repo,
                    "pr_number": pr_number_int,
                    "reason": reason,
                    "file_count": len(file_paths),
                    "sample_paths": sample_paths,
                }
            )
            return True, f"file_path_skip:{reason}", {"file_count": len(file_paths), "sample_paths": sample_paths}

    return False, "passed_all_filters", {}


def is_internal_repo_allowed(repo: str) -> bool:
    """
    Check if an internal repo is allowed for AI review in Staging.

    Phase B-B: Internal Repo Dogfooding
    This enables MorningAI to review its own code in Staging environment.

    Preconditions (all must be true):
    1. settings object is available
    2. allow_internal_repos_in_staging is True
    3. is_staging environment is True
    4. repo is in internal_repos_whitelist

    Args:
        repo: Repository in owner/repo format (e.g., 'RC918/morningai')

    Returns:
        True if the repo is an internal repo and dogfooding is enabled in Staging
    """
    if not settings:
        return False

    # Gather all preconditions using getattr for robustness
    is_staging_env = getattr(settings, 'is_staging', False)
    allow_internal = getattr(settings, 'allow_internal_repos_in_staging', False)
    whitelist_str = getattr(settings, 'internal_repos_whitelist', '')

    # Dogfooding is only allowed when all preconditions are met
    if not (allow_internal and is_staging_env and whitelist_str):
        return False

    # Parse whitelist and check if repo is allowed
    whitelist = {r.strip() for r in whitelist_str.split(',') if r.strip()}
    is_allowed = repo in whitelist

    if is_allowed:
        logger.info(
            "[EventNormalizer] Internal repo allowed for AI review (dogfooding)",
            extra={
                "operation": "internal_repo_dogfooding",
                "repo": repo,
                "is_staging": is_staging_env,
            }
        )

    return is_allowed


@dataclass
class PRUpdatedAllowedResult:
    """Result of PR_UPDATED allowed check"""
    is_allowed: bool
    reason: str
    should_schedule_job: bool = False
    job_token: Optional[str] = None
    debounce_seconds: int = 30


def is_pr_updated_allowed(repo: str, pr_number: int, redis_url: str = None) -> PRUpdatedAllowedResult:
    """
    Check if a PR_UPDATED event should trigger a delayed review job.

    Phase B-B: PR_UPDATED Event Support with Debounce/Throttle
    This enables AI review on PR updates (push events) with cost protection.

    CRITICAL FIX: Now returns should_schedule_job=True for first event,
    allowing caller to enqueue a delayed job that sleeps then processes.

    Preconditions (all must be true):
    1. settings.enable_pr_updated_review is True
    2. repo is in pr_updated_repos_whitelist (or whitelist is empty = all repos)
    3. Debounce check passes (first event or debounce window expired)
    4. Throttle check passes (not reviewed too recently)

    Args:
        repo: Repository in owner/repo format (e.g., 'RC918/morningai')
        pr_number: Pull request number
        redis_url: Optional Redis URL for debounce/throttle tracking

    Returns:
        PRUpdatedAllowedResult with:
        - is_allowed: True if event should trigger review workflow
        - should_schedule_job: True if caller should enqueue delayed job
        - job_token: Token to pass to delayed job for verification
        - debounce_seconds: Debounce window for delayed job sleep
        - reason: Human-readable explanation
    """
    if not settings:
        return PRUpdatedAllowedResult(
            is_allowed=False,
            reason="settings_unavailable",
        )

    enable_pr_updated = getattr(settings, 'enable_pr_updated_review', False)
    if not enable_pr_updated:
        return PRUpdatedAllowedResult(
            is_allowed=False,
            reason="pr_updated_review_disabled",
        )

    whitelist_str = getattr(settings, 'pr_updated_repos_whitelist', '')
    if whitelist_str:
        whitelist = {r.strip() for r in whitelist_str.split(',') if r.strip()}
        if repo not in whitelist:
            return PRUpdatedAllowedResult(
                is_allowed=False,
                reason="repo_not_in_whitelist",
            )

    debounce_seconds = getattr(settings, 'pr_updated_debounce_seconds', 30)
    throttle_seconds = getattr(settings, 'pr_updated_throttle_seconds', 600)

    debounce_result = check_pr_updated_debounce(
        repo=repo,
        pr_number=pr_number,
        debounce_seconds=debounce_seconds,
        throttle_seconds=throttle_seconds,
        redis_url=redis_url,
    )

    if debounce_result.should_schedule_job:
        logger.info(
            "[EventNormalizer] PR_UPDATED event - scheduling delayed job",
            extra={
                "operation": "pr_updated_schedule_job",
                "repo": repo,
                "pr_number": pr_number,
                "job_token": debounce_result.job_token,
                "debounce_seconds": debounce_seconds,
            }
        )
        return PRUpdatedAllowedResult(
            is_allowed=True,
            reason="first_event: delayed job scheduled",
            should_schedule_job=True,
            job_token=debounce_result.job_token,
            debounce_seconds=debounce_seconds,
        )

    logger.info(
        "[EventNormalizer] PR_UPDATED event debounced/throttled",
        extra={
            "operation": "pr_updated_debounce_check",
            "repo": repo,
            "pr_number": pr_number,
            "reason": debounce_result.reason,
        }
    )
    return PRUpdatedAllowedResult(
        is_allowed=False,
        reason=debounce_result.reason,
    )


@dataclass
class NormalizedTask:
    """
    A task extracted from a webhook event, ready for Meta Agent processing.

    This represents the bridge between external events and internal task execution.
    """
    task_id: str
    source_event: WebhookEvent
    goal_text: str
    priority: str
    requires_approval: bool
    context: Dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.now)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization"""
        return {
            "task_id": self.task_id,
            "source_event_id": self.source_event.event_id,
            "source": self.source_event.source.value,
            "event_type": self.source_event.event_type.value,
            "goal_text": self.goal_text,
            "priority": self.priority,
            "requires_approval": self.requires_approval,
            "context": self.context,
            "created_at": self.created_at.isoformat(),
        }


class EventNormalizer:
    """
    Normalizes webhook events from different sources into a unified format
    and prepares them for Meta Agent processing.

    This class:
    1. Routes events to appropriate handlers based on source
    2. Validates and normalizes event data
    3. Extracts actionable tasks from events
    4. Determines priority and approval requirements
    """

    # Event types that typically require human approval
    HIGH_RISK_EVENT_TYPES = {
        WebhookEventType.PR_MERGED,
        WebhookEventType.ISSUE_CLOSED,
        WebhookEventType.BRANCH_DELETED,
    }

    # Event types that are actionable (can trigger Meta Agent tasks)
    # P0: PR_COMMENTED removed to prevent self-trigger loop (CTO decision 2025-12-22)
    # MorningAI is a "one-way reviewer", not a "conversational chatbot"
    # See: EPIC B - GitHub App migration for future Identity Filter support
    ACTIONABLE_EVENT_TYPES = {
        WebhookEventType.ISSUE_CREATED,
        WebhookEventType.ISSUE_COMMENTED,
        WebhookEventType.ISSUE_ASSIGNED,
        WebhookEventType.PR_OPENED,
        WebhookEventType.PR_REVIEWED,
        # WebhookEventType.PR_COMMENTED,  # DISABLED: causes self-trigger loop
        WebhookEventType.MENTION_RECEIVED,
        WebhookEventType.COMMAND_RECEIVED,
    }

    # AI Reviewer standard phrases that indicate actionable feedback
    # Issue: #2209 - 修復 AI Reviewer 評論接收機制
    # Note: Removed overly generic keywords (refactor, simplify, optimize)
    # to avoid false positives from human comments
    AI_REVIEWER_KEYWORDS = [
        # Codex / Copilot standard phrases
        "suggestion:", "consider:", "recommend:", "could be improved",
        "potential issue", "possible bug", "code smell",
        # Gemini Code Assist standard phrases
        "code review", "improvement suggestion", "best practice",
        "security concern", "performance issue", "maintainability",
        # CodeRabbit standard phrases
        "actionable comment", "nitpick:", "issue:",
        # General AI reviewer phrases (specific, not generic)
        "fix:", "bug:", "vulnerability", "deprecated", "unused", "dead code",
    ]

    # Priority mapping based on labels
    PRIORITY_LABELS = {
        "critical": ["critical", "urgent", "p0", "blocker", "緊急"],
        "high": ["high", "important", "p1", "高優先"],
        "medium": ["medium", "normal", "p2", "中優先"],
        "low": ["low", "minor", "p3", "低優先"],
    }

    def __init__(
        self,
        github_config: Optional[WebhookConfig] = None,
        jira_config: Optional[WebhookConfig] = None,
        linear_config: Optional[WebhookConfig] = None,
        slack_config: Optional[WebhookConfig] = None,
    ):
        """
        Initialize the EventNormalizer with handler configurations.

        Args:
            github_config: Configuration for GitHub webhook handler
            jira_config: Configuration for Jira webhook handler
            linear_config: Configuration for Linear webhook handler
            slack_config: Configuration for Slack webhook handler
        """
        self.handlers: Dict[WebhookSource, BaseWebhookHandler] = {
            WebhookSource.GITHUB: GitHubWebhookHandler(github_config),
            WebhookSource.JIRA: JiraWebhookHandler(jira_config),
            WebhookSource.LINEAR: LinearWebhookHandler(linear_config),
            WebhookSource.SLACK: SlackWebhookHandler(slack_config),
        }

        # Initialize Comment Triage Agent for AI reviewer comment classification
        # Issue: #2210 - Comment Triage Agent 設計與實作
        self.comment_triage_agent = CommentTriageAgent()

        # Initialize Command Router for /morningai command handling
        # Issue: #3224 - PR Comment Command Router
        self.command_router = CommandRouter()

        logger.info(
            "[EventNormalizer] Initialized with handlers: %s",
            list(self.handlers.keys()),
        )

    def get_handler(self, source: WebhookSource) -> Optional[BaseWebhookHandler]:
        """
        Get the handler for a specific webhook source.

        Args:
            source: Webhook source

        Returns:
            Handler instance or None if not configured
        """
        return self.handlers.get(source)

    def process_webhook(
        self,
        source: WebhookSource,
        headers: Dict[str, str],
        payload: bytes,
        parsed_payload: Dict[str, Any],
    ) -> WebhookResponse:
        """
        Process a webhook request from any supported source.

        Args:
            source: Webhook source (github, jira, slack)
            headers: Request headers
            payload: Raw request body
            parsed_payload: Parsed JSON payload

        Returns:
            WebhookResponse with processing result
        """
        handler = self.get_handler(source)
        if not handler:
            logger.warning("[EventNormalizer] No handler for source: %s", source)
            return WebhookResponse(
                success=False,
                message=f"Unsupported webhook source: {source.value}",
                errors=[f"No handler configured for {source.value}"],
            )

        return handler.handle(headers, payload, parsed_payload)

    def parse_event(
        self,
        source: WebhookSource,
        headers: Dict[str, str],
        payload: Dict[str, Any],
    ) -> Optional[WebhookEvent]:
        """
        Parse a webhook payload into a normalized WebhookEvent.

        Args:
            source: Webhook source
            headers: Request headers
            payload: Parsed JSON payload

        Returns:
            Normalized WebhookEvent or None if parsing fails
        """
        handler = self.get_handler(source)
        if not handler:
            logger.warning("[EventNormalizer] No handler for source: %s", source)
            return None

        try:
            return handler.parse_event(headers, payload)
        except Exception as e:
            logger.exception(
                "[EventNormalizer] Failed to parse event from %s: %s",
                source.value,
                e,
            )
            return None

    def is_actionable(self, event: WebhookEvent) -> bool:
        """
        Determine if an event is actionable (should trigger Meta Agent).

        Args:
            event: Normalized webhook event

        Returns:
            True if event should trigger task creation

        Issue: #2209 - 修復 AI Reviewer 評論接收機制
        Issue: #2254 - is_actionable observability
        Phase B-B: Internal Repo Dogfooding support
        Issue: Self-Trigger Loop Prevention
        Issue: Garbage PR Fix (Dec 2025)
        """
        # P0: UNKNOWN Event Filter - Skip events that couldn't be parsed
        # Issue: Garbage PR Fix (Dec 2025)
        # When GitHub sends events not in GITHUB_EVENT_MAP (e.g., check_suite, check_run, status),
        # they are parsed as UNKNOWN. Without this check, UNKNOWN events can bypass
        # should_skip_orchestrator_pr_event() and trigger garbage PR creation via keyword matching.
        # This is a critical early-exit to prevent self-trigger loops from non-PR events.
        if event.event_type == WebhookEventType.UNKNOWN:
            repo = f"{event.repo_owner}/{event.repo_name}" if event.repo_owner and event.repo_name else "unknown"
            # Staging observation logging (#3047) - capture metadata for analysis
            metadata = event.metadata or {}
            github_event = metadata.get("github_event", "unknown")
            github_action = metadata.get("action", "unknown")
            raw_payload = event.raw_payload or {}
            head_branch = _extract_head_branch_from_payload(raw_payload)
            logger.info(
                "[EventNormalizer] UNKNOWN event skipped - not actionable",
                extra={
                    "operation": "unknown_event_skip",
                    "event_id": event.event_id,
                    "repo": repo,
                    "event_type": event.event_type.value,
                    "github_event": github_event,
                    "github_action": github_action,
                    "head_branch": head_branch,
                    "actor": event.actor_name or "unknown",
                    "reason": "unknown_event_type_not_actionable",
                }
            )
            return False

        # P1: Self-Review Detection - Skip our own reviews to prevent feedback loop
        # Issue: Self-Trigger Loop Prevention
        # When the orchestrator posts a review, GitHub sends a PR_REVIEWED webhook.
        # Without this check, we would process our own review and create an infinite loop.
        if is_self_generated_review(event):
            return False

        # P2: Orchestrator Branch Detection - Skip PRs from orchestrator/* branches
        # Issue: Docs PR Noise Reduction
        # When the orchestrator creates a docs PR, GitHub sends PR webhooks back.
        # Without this check, we would process our own PRs and create more noise.
        if should_skip_orchestrator_pr_event(event):
            return False

        # Issue: #3366 - CI Failure Reflex Integration
        # Handle CI_CHECK_COMPLETED events with dedicated logic (early branch)
        # This MUST be processed BEFORE Smart PR Filtering to avoid false skips
        # CI events have different actionability criteria than PR events
        if event.event_type == WebhookEventType.CI_CHECK_COMPLETED:
            return self._handle_ci_check_completed(event)

        # Smart PR Filtering - Skip PRs that don't warrant documentation
        # Smart PR Filtering (Dec 2025)
        # This filter reduces noise by skipping PRs that only modify:
        # - Config files (yaml, json, toml, etc.)
        # - Documentation files (md, rst, txt)
        # - Test files (tests/*, *_test.py, *.spec.ts)
        # - CI/CD files (.github/*)
        # Or PRs with non-actionable title prefixes (chore:, ci:, test:, docs:, style:)
        should_skip, _, _ = should_skip_pr_by_smart_filters(event)
        if should_skip:
            return False

        # P0: Disable PR_COMMENTED events entirely (CTO decision 2025-12-22)
        # This is a hard block that cannot be bypassed by is_ai_reviewer or other logic.
        # MorningAI is a "one-way reviewer", not a "conversational chatbot".
        # Without this, inline review comments trigger webhooks that cause infinite loops.
        # See: EPIC B - GitHub App migration for future Identity Filter support
        if event.event_type == WebhookEventType.PR_COMMENTED:
            repo = f"{event.repo_owner}/{event.repo_name}" if event.repo_owner and event.repo_name else "unknown"
            logger.debug(
                "[EventNormalizer] PR_COMMENTED event skipped (conversational review disabled)",
                extra={
                    "operation": "pr_commented_disabled",
                    "event_id": event.event_id,
                    "repo": repo,
                    "pr_number": event.resource_id or "unknown",
                    "actor": event.actor_name,
                    "reason": "no_conversational_review",
                }
            )
            return False

        is_ai_reviewer = bool(event.metadata.get("is_ai_reviewer"))
        bot_name = event.metadata.get("review_source", "unknown") if is_ai_reviewer else None
        repo = f"{event.repo_owner}/{event.repo_name}" if event.repo_owner and event.repo_name else "unknown"
        pr_number = event.resource_id or "unknown"
        matched_keywords: List[str] = []
        is_actionable_result = False
        actionable_reason = ""
        is_internal_repo = is_internal_repo_allowed(repo)

        # Check if event type is in actionable list
        if event.event_type in self.ACTIONABLE_EVENT_TYPES:
            is_actionable_result = True
            actionable_reason = "event_type_actionable"

        # Phase B-B: Check if PR_UPDATED event is allowed (with debounce/throttle)
        # PR_UPDATED is NOT in ACTIONABLE_EVENT_TYPES by default to prevent cost explosion
        # It requires explicit enablement via settings and passes debounce/throttle checks
        elif event.event_type == WebhookEventType.PR_UPDATED:
            try:
                pr_number_int = int(pr_number) if pr_number != "unknown" else 0
            except (ValueError, TypeError):
                pr_number_int = 0

            if pr_number_int > 0:
                pr_updated_result = is_pr_updated_allowed(
                    repo=repo,
                    pr_number=pr_number_int,
                )
                if pr_updated_result.is_allowed:
                    is_actionable_result = True
                    actionable_reason = f"pr_updated_allowed:{pr_updated_result.reason}"
                    event.metadata["pr_updated_should_schedule_job"] = pr_updated_result.should_schedule_job
                    event.metadata["pr_updated_job_token"] = pr_updated_result.job_token
                    event.metadata["pr_updated_debounce_seconds"] = pr_updated_result.debounce_seconds
                    logger.info(
                        "[EventNormalizer] PR_UPDATED event is actionable",
                        extra={
                            "operation": "pr_updated_actionable",
                            "event_id": event.event_id,
                            "repo": repo,
                            "pr_number": pr_number,
                            "should_schedule_job": pr_updated_result.should_schedule_job,
                            "job_token": pr_updated_result.job_token,
                        }
                    )
                else:
                    logger.debug(
                        "[EventNormalizer] PR_UPDATED event not actionable: %s",
                        pr_updated_result.reason,
                        extra={
                            "operation": "pr_updated_not_actionable",
                            "event_id": event.event_id,
                            "repo": repo,
                            "pr_number": pr_number,
                            "reason": pr_updated_result.reason,
                        }
                    )

        # Check if event is from an AI reviewer (always actionable)
        # Issue: #2209 - AI reviewer events should be processed
        elif is_ai_reviewer:
            is_actionable_result = True
            actionable_reason = "ai_reviewer_event"

        else:
            # Check for specific keywords in title/description
            text = f"{event.title or ''} {event.description or ''}".lower()
            action_keywords = [
                "fix", "implement", "add", "create", "update", "refactor",
                "修復", "實現", "新增", "建立", "更新", "重構",
                "@bot", "@agent", "@meta-agent",
            ]

            for keyword in action_keywords:
                if keyword in text:
                    matched_keywords.append(keyword)
                    is_actionable_result = True
                    actionable_reason = "action_keyword_match"
                    break

            # Check for AI reviewer standard phrases
            # Issue: #2209 - Recognize AI reviewer standard terminology
            if not is_actionable_result:
                for keyword in self.AI_REVIEWER_KEYWORDS:
                    if keyword in text:
                        matched_keywords.append(keyword)
                        is_actionable_result = True
                        actionable_reason = "ai_reviewer_keyword_match"
                        logger.debug(
                            "[EventNormalizer] AI reviewer keyword detected: %s",
                            keyword,
                        )
                        break

        # Issue: #2254 - Structured logging for is_actionable observability
        # Log all AI reviewer comment processing for false positive monitoring
        if is_ai_reviewer:
            logger.info(
                "[EventNormalizer] AI reviewer comment processed",
                extra={
                    "operation": "ai_reviewer_is_actionable",
                    "event_id": event.event_id,
                    "is_actionable": is_actionable_result,
                    "bot_name": bot_name,
                    "repo": repo,
                    "pr_number": pr_number,
                    "matched_keywords": matched_keywords,
                    "actionable_reason": actionable_reason,
                    "is_internal_repo": is_internal_repo,
                }
            )

        # Phase B-B: Log internal repo events for dogfooding observability
        if is_internal_repo:
            logger.info(
                "[EventNormalizer] Internal repo event processed (dogfooding)",
                extra={
                    "operation": "internal_repo_event",
                    "event_id": event.event_id,
                    "is_actionable": is_actionable_result,
                    "repo": repo,
                    "pr_number": pr_number,
                    "event_type": event.event_type.value,
                    "actionable_reason": actionable_reason,
                }
            )

        return is_actionable_result

    def extract_task(self, event: WebhookEvent) -> Optional[NormalizedTask]:
        """
        Extract an actionable task from a webhook event.

        Args:
            event: Normalized webhook event

        Returns:
            NormalizedTask ready for Meta Agent, or None if not actionable
        """
        if not self.is_actionable(event):
            logger.debug(
                "[EventNormalizer] Event %s is not actionable",
                event.event_id,
            )
            return None

        # Generate goal text from event
        goal_text = event.to_goal_text()

        # Determine priority
        priority = self._determine_priority(event)

        # Determine if approval is required
        requires_approval = self._requires_approval(event)

        # Build context for Meta Agent
        context = self._build_context(event)

        # Generate task ID with full UUID for DB compatibility
        # Format: webhook-{source}-{full_uuid}
        # The db_writer.normalize_and_validate_uuid() will extract the UUID portion
        import uuid
        task_uuid = str(uuid.uuid4())
        task_id = f"webhook-{event.source.value}-{task_uuid}"

        task = NormalizedTask(
            task_id=task_id,
            source_event=event,
            goal_text=goal_text,
            priority=priority,
            requires_approval=requires_approval,
            context=context,
        )

        logger.info(
            "[EventNormalizer] Extracted task: id=%s, priority=%s, approval=%s",
            task_id,
            priority,
            requires_approval,
        )

        return task

    def _determine_priority(self, event: WebhookEvent) -> str:
        """
        Determine task priority from event labels and content.

        Args:
            event: Normalized webhook event

        Returns:
            Priority string (critical, high, medium, low)
        """
        # Check event priority field first
        if event.priority:
            return event.priority

        # Check labels
        labels_lower = [label.lower() for label in event.labels]
        for priority, keywords in self.PRIORITY_LABELS.items():
            for keyword in keywords:
                if keyword in labels_lower:
                    return priority

        # Check title/description for priority keywords
        text = f"{event.title or ''} {event.description or ''}".lower()
        for priority, keywords in self.PRIORITY_LABELS.items():
            for keyword in keywords:
                if keyword in text:
                    return priority

        # Default to medium
        return "medium"

    def _requires_approval(self, event: WebhookEvent) -> bool:
        """
        Determine if task requires human approval.

        Args:
            event: Normalized webhook event

        Returns:
            True if approval is required
        """
        # High-risk event types always require approval
        if event.event_type in self.HIGH_RISK_EVENT_TYPES:
            return True

        # Check for high-risk keywords
        text = f"{event.title or ''} {event.description or ''}".lower()
        high_risk_keywords = [
            "production", "deploy", "delete", "remove", "drop",
            "生產", "部署", "刪除", "移除",
            "security", "credential", "secret", "password",
            "安全", "憑證", "密碼",
        ]

        for keyword in high_risk_keywords:
            if keyword in text:
                return True

        return False

    def _build_context(self, event: WebhookEvent) -> Dict[str, Any]:
        """
        Build context dictionary for Meta Agent.

        Args:
            event: Normalized webhook event

        Returns:
            Context dictionary with relevant information
        """
        context = {
            "source": event.source.value,
            "event_type": event.event_type.value,
            "event_id": event.event_id,
            "url": event.url,
            "actor": event.actor_name,
        }

        # Add repository context
        if event.repo_owner and event.repo_name:
            context["repo"] = f"{event.repo_owner}/{event.repo_name}"

        # Add project context (for Jira)
        if event.project_key:
            context["project"] = event.project_key

        # Add resource context
        # Fix: Decouple resource_type from resource_id - they should be added independently
        # Previously, resource_type was only added if resource_id was truthy, causing
        # resource_type to be missing when resource_id was empty string or None
        if event.resource_type:
            context["resource_type"] = event.resource_type
        if event.resource_id:
            context["resource_id"] = event.resource_id

        # Add labels and assignees
        if event.labels:
            context["labels"] = event.labels
        if event.assignees:
            context["assignees"] = event.assignees

        # Phase B-B: Pass PR_UPDATED debounce metadata to task context
        # This enables the webhook handler to enqueue delayed jobs
        if event.metadata.get("pr_updated_should_schedule_job"):
            context["pr_updated_should_schedule_job"] = event.metadata["pr_updated_should_schedule_job"]
            context["pr_updated_job_token"] = event.metadata.get("pr_updated_job_token")
            context["pr_updated_debounce_seconds"] = event.metadata.get("pr_updated_debounce_seconds")

        # Issue: #3366 - Pass CI failure metadata to task context
        # This enables the webhook handler to route CI failure events to auto-fix flow
        # _handle_ci_check_completed() sets these in event.metadata, but they must be
        # passed to task.context for _enqueue_task() to detect and route correctly
        if event.metadata.get("ci_failure_trigger"):
            context["ci_failure_trigger"] = event.metadata.get("ci_failure_trigger")
            context["ci_failure_pr_number"] = event.metadata.get("ci_failure_pr_number")
            context["ci_failure_dedup_key"] = event.metadata.get("ci_failure_dedup_key")

        return context

    def batch_process(
        self,
        events: List[WebhookEvent],
    ) -> List[NormalizedTask]:
        """
        Process multiple events and extract actionable tasks.

        Args:
            events: List of normalized webhook events

        Returns:
            List of extracted tasks
        """
        tasks = []
        for event in events:
            task = self.extract_task(event)
            if task:
                tasks.append(task)

        logger.info(
            "[EventNormalizer] Batch processed %d events, extracted %d tasks",
            len(events),
            len(tasks),
        )

        return tasks

    def triage_comment(
        self, event: WebhookEvent, redis_url: Optional[str] = None
    ) -> Optional[CommentTriageResult]:
        """
        Triage an AI reviewer comment event with rate limiting.

        This method first checks rate limits, then delegates to the
        CommentTriageAgent to classify the comment, assess risk, and
        determine if it should be auto-fixed.

        Args:
            event: WebhookEvent with is_ai_reviewer=True in metadata
            redis_url: Optional Redis URL for rate limiting

        Returns:
            CommentTriageResult with classification and recommendations,
            or None if the event is not from an AI reviewer or rate limited

        Issue: #2210 - Comment Triage Agent 設計與實作
        Issue: #2253 - AI Reviewer Rate Limiting
        """
        is_ai_reviewer = bool(event.metadata.get("is_ai_reviewer"))

        if is_ai_reviewer:
            repo = f"{event.repo_owner}/{event.repo_name}" if event.repo_owner and event.repo_name else "unknown"
            pr_id = f"{repo}#{event.resource_id}" if event.resource_id else f"{repo}#unknown"
            bot_name = event.metadata.get("review_source", "unknown")

            rate_limit_result = check_ai_reviewer_rate_limit(
                pr_id=pr_id,
                repo=repo,
                bot_name=bot_name,
                redis_url=redis_url,
            )

            if not rate_limit_result.allowed:
                logger.warning(
                    "[EventNormalizer] AI reviewer comment rate limited",
                    extra={
                        "operation": "ai_reviewer_rate_limited",
                        "event_id": event.event_id,
                        "pr_id": pr_id,
                        "repo": repo,
                        "bot_name": bot_name,
                        "exceeded_dimension": rate_limit_result.exceeded_dimension,
                        "current_count": rate_limit_result.current_count,
                        "limit": rate_limit_result.limit,
                    }
                )
                return None

        return self.comment_triage_agent.triage(event)

    def batch_triage_comments(
        self, events: List[WebhookEvent], redis_url: Optional[str] = None
    ) -> List[CommentTriageResult]:
        """
        Triage multiple AI reviewer comment events with rate limiting.

        Args:
            events: List of WebhookEvents
            redis_url: Optional Redis URL for rate limiting

        Returns:
            List of CommentTriageResults for AI reviewer events (rate limited events excluded)

        Issue: #2210 - Comment Triage Agent 設計與實作
        Issue: #2253 - AI Reviewer Rate Limiting
        """
        results = []
        for event in events:
            result = self.triage_comment(event, redis_url=redis_url)
            if result:
                results.append(result)
        return results

    def route_command(self, event: WebhookEvent) -> Optional[CommandTrigger]:
        """
        Route a /morningai command from a PR comment event.

        This method checks if a comment event contains a /morningai command
        and returns a CommandTrigger that can be used to trigger the appropriate
        flow (e.g., reviewer_node for /morningai review).

        Args:
            event: WebhookEvent from a comment (ISSUE_COMMENTED or PR_COMMENTED)

        Returns:
            CommandTrigger if event contains a valid /morningai command,
            None otherwise (event should continue to normal processing)

        Issue: #3224 - PR Comment Command Router
        Blueprint: Track C interface standardization
        """
        return self.command_router.route(event)

    def is_command_comment(self, event: WebhookEvent) -> bool:
        """
        Quick check if an event might contain a /morningai command.

        This is a lightweight check that can be used before full routing
        to avoid unnecessary processing.

        Args:
            event: WebhookEvent to check

        Returns:
            True if event might contain a /morningai command

        Issue: #3224 - PR Comment Command Router
        """
        return self.command_router.is_command_comment(event)

    # Issue: #3366 - CI Failure Reflex Integration
    # Issue: #3399 - Redis-backed dedup for cross-worker idempotency
    # Redis key prefix for CI failure dedup
    _CI_FAILURE_DEDUP_KEY_PREFIX = "orchestrator:ci_failure_dedup"
    _CI_FAILURE_DEDUP_TTL_SECONDS = 3600  # 1 hour TTL

    # Fallback in-memory dedup (used when Redis is unavailable)
    # This is process-local and won't work across workers, but provides
    # at-least-once semantics when Redis is down
    _ci_failure_dedup_fallback: Dict[str, float] = {}
    _CI_FAILURE_DEDUP_FALLBACK_MAX_SIZE = 1000  # Max entries for fallback

    def _handle_ci_check_completed(self, event: WebhookEvent) -> bool:
        """
        Handle CI_CHECK_COMPLETED events for CI failure reflex.

        This method implements the CI failure reflex logic:
        1. Skip if conclusion is not "failure"
        2. Skip if no PR is associated (non-PR CI)
        3. Skip orchestrator/* and devin/* branches
        4. Dedup: same PR + same head SHA only triggers once
        5. Mark event metadata for downstream processing

        Args:
            event: WebhookEvent with CI_CHECK_COMPLETED type

        Returns:
            True if CI failure should trigger auto-fix, False otherwise

        Issue: #3366 - CI Failure Reflex Integration
        """
        # Ensure metadata is a dict (defensive, in case it's None)
        if event.metadata is None:
            event.metadata = {}
        metadata = event.metadata
        repo = f"{event.repo_owner}/{event.repo_name}" if event.repo_owner and event.repo_name else "unknown"

        # Extract CI-specific metadata
        conclusion = metadata.get("ci_conclusion", "")
        head_branch = metadata.get("ci_head_branch", "")
        head_sha = metadata.get("ci_head_sha", "")
        pr_numbers = metadata.get("ci_pr_numbers", [])

        # P0: Skip if conclusion is not "failure"
        # Only trigger auto-fix for actual failures, not success/cancelled/etc.
        if conclusion != "failure":
            logger.info(
                "[EventNormalizer] CI check skipped - not a failure",
                extra={
                    "operation": "ci_check_skip_non_failure",
                    "event_id": event.event_id,
                    "repo": repo,
                    "conclusion": conclusion,
                    "head_branch": head_branch,
                    "head_sha": head_sha[:8] if head_sha else "unknown",
                }
            )
            return False

        # P1: Skip if no PR is associated (non-PR CI, e.g., push to main)
        if not pr_numbers:
            logger.info(
                "[EventNormalizer] CI failure skipped - no associated PR",
                extra={
                    "operation": "ci_failure_skip_no_pr",
                    "event_id": event.event_id,
                    "repo": repo,
                    "conclusion": conclusion,
                    "head_branch": head_branch,
                    "head_sha": head_sha[:8] if head_sha else "unknown",
                }
            )
            return False

        # P2: Skip orchestrator/* and devin/* branches to prevent self-trigger loops
        # These are branches created by the orchestrator for auto-fix PRs
        if head_branch:
            branch_lower = head_branch.lower()
            if branch_lower.startswith("orchestrator/") or branch_lower.startswith("devin/"):
                logger.info(
                    "[EventNormalizer] CI failure skipped - orchestrator/devin branch",
                    extra={
                        "operation": "ci_failure_skip_orchestrator_branch",
                        "event_id": event.event_id,
                        "repo": repo,
                        "head_branch": head_branch,
                        "pr_numbers": pr_numbers,
                        "reason": "self_trigger_prevention",
                    }
                )
                return False

        # P3: Dedup - same PR + same head SHA only triggers once
        # This prevents duplicate triggers from webhook retries or re-runs
        # Issue: #3399 - Redis-backed dedup for cross-worker idempotency
        pr_number = pr_numbers[0]  # Use first PR for dedup key
        dedup_key = f"{repo}:{pr_number}:{head_sha}"

        # Try Redis-backed dedup first (cross-worker idempotency)
        is_duplicate, dedup_source = self._check_ci_failure_dedup_redis(
            dedup_key, event.event_id, repo, pr_number, head_sha
        )

        if is_duplicate:
            logger.info(
                "[EventNormalizer] CI failure skipped - already processed (dedup)",
                extra={
                    "operation": "ci_failure_skip_dedup",
                    "event_id": event.event_id,
                    "repo": repo,
                    "pr_number": pr_number,
                    "head_sha": head_sha[:8] if head_sha else "unknown",
                    "dedup_key": dedup_key,
                    "dedup_source": dedup_source,
                }
            )
            return False

        # Mark event metadata for downstream processing
        event.metadata["ci_failure_trigger"] = True
        event.metadata["ci_failure_pr_number"] = pr_number
        event.metadata["ci_failure_dedup_key"] = dedup_key

        logger.info(
            "[EventNormalizer] CI failure is actionable - triggering auto-fix",
            extra={
                "operation": "ci_failure_actionable",
                "event_id": event.event_id,
                "repo": repo,
                "pr_number": pr_number,
                "head_branch": head_branch,
                "head_sha": head_sha[:8] if head_sha else "unknown",
                "conclusion": conclusion,
            }
        )

        return True

    def _check_ci_failure_dedup_redis(
        self,
        dedup_key: str,
        event_id: str,
        repo: str,
        pr_number: int,
        head_sha: str
    ) -> tuple:
        """
        Check if CI failure event is a duplicate using Redis-backed dedup.

        Uses atomic SET NX EX for race-safe deduplication across workers.
        Falls back to in-memory dedup if Redis is unavailable.

        Args:
            dedup_key: Unique key for dedup (repo:pr:sha)
            event_id: Event ID for logging
            repo: Repository name
            pr_number: PR number
            head_sha: Head SHA

        Returns:
            Tuple of (is_duplicate: bool, source: str)
            - is_duplicate: True if this event was already processed
            - source: "redis" or "fallback" indicating which dedup was used

        Issue: #3399 - Redis-backed dedup for cross-worker idempotency
        """
        redis_key = f"{self._CI_FAILURE_DEDUP_KEY_PREFIX}:{dedup_key}"

        # Try Redis first
        try:
            redis_client = self._get_redis_client_for_dedup()
            if redis_client:
                # Atomic SET NX EX - returns True if key was set (first time)
                # Returns False if key already exists (duplicate)
                is_new = redis_client.set(
                    redis_key,
                    "1",
                    nx=True,  # Only set if not exists
                    ex=self._CI_FAILURE_DEDUP_TTL_SECONDS  # TTL in seconds
                )

                if is_new:
                    # First time seeing this event - not a duplicate
                    logger.debug(
                        "[EventNormalizer] CI failure dedup - new event (Redis)",
                        extra={
                            "operation": "ci_failure_dedup_new",
                            "event_id": event_id,
                            "dedup_key": dedup_key,
                            "source": "redis",
                        }
                    )
                    return (False, "redis")
                else:
                    # Key already exists - duplicate
                    return (True, "redis")

        except Exception as e:
            # Redis error - log and fall back to in-memory
            logger.warning(
                "[EventNormalizer] CI failure dedup Redis error - falling back to in-memory",
                extra={
                    "operation": "ci_failure_dedup_redis_error",
                    "event_id": event_id,
                    "dedup_key": dedup_key,
                    "error": str(e),
                }
            )

        # Fallback to in-memory dedup (process-local)
        return self._check_ci_failure_dedup_fallback(
            dedup_key, event_id, repo, pr_number, head_sha
        )

    def _check_ci_failure_dedup_fallback(
        self,
        dedup_key: str,
        event_id: str,
        repo: str,
        pr_number: int,
        head_sha: str
    ) -> tuple:
        """
        Fallback in-memory dedup when Redis is unavailable.

        This is process-local and won't work across workers, but provides
        at-least-once semantics when Redis is down.

        Args:
            dedup_key: Unique key for dedup
            event_id: Event ID for logging
            repo: Repository name
            pr_number: PR number
            head_sha: Head SHA

        Returns:
            Tuple of (is_duplicate: bool, source: str)

        Issue: #3399 - Fallback for Redis unavailable
        """
        current_time = time.time()

        # Clean up expired entries (simple TTL cleanup)
        expired_keys = [
            k for k, v in self._ci_failure_dedup_fallback.items()
            if current_time - v > self._CI_FAILURE_DEDUP_TTL_SECONDS
        ]
        for k in expired_keys:
            del self._ci_failure_dedup_fallback[k]

        # Check if already processed
        if dedup_key in self._ci_failure_dedup_fallback:
            return (True, "fallback")

        # Enforce max size to prevent memory bloat
        if len(self._ci_failure_dedup_fallback) >= self._CI_FAILURE_DEDUP_FALLBACK_MAX_SIZE:
            # Remove oldest entries (FIFO)
            oldest_keys = sorted(
                self._ci_failure_dedup_fallback.keys(),
                key=lambda k: self._ci_failure_dedup_fallback[k]
            )[:100]  # Remove 100 oldest
            for k in oldest_keys:
                del self._ci_failure_dedup_fallback[k]

        # Mark as processed
        self._ci_failure_dedup_fallback[dedup_key] = current_time

        logger.debug(
            "[EventNormalizer] CI failure dedup - new event (fallback)",
            extra={
                "operation": "ci_failure_dedup_new",
                "event_id": event_id,
                "dedup_key": dedup_key,
                "source": "fallback",
            }
        )

        return (False, "fallback")

    def _get_redis_client_for_dedup(self):
        """
        Get Redis client for CI failure deduplication.

        Returns:
            Redis client instance or None if unavailable

        Issue: #3399 - Redis-backed dedup for cross-worker idempotency
        """
        try:
            import redis

            try:
                from common.config.settings import settings
                url = getattr(settings, 'redis_url', None)
            except ImportError:
                import os
                url = os.environ.get('REDIS_URL')

            if url:
                return redis.Redis.from_url(url, decode_responses=True)
            else:
                logger.debug("[EventNormalizer] No Redis URL configured for CI dedup")
                return None
        except Exception as e:
            logger.warning(f"[EventNormalizer] Failed to connect to Redis for CI dedup: {e}")
            return None
