version: '3.8'

services:
  mcp-server:
    build: ../../
    command: python mcp/server.py
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=${REDIS_URL}
      - RENDER_API_KEY=${RENDER_API_KEY}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
    networks:
      - agent-network
  
  ops-agent-sandbox:
    build: .
    container_name: ops-agent-sandbox-dev
    depends_on:
      - mcp-server
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2048M
          pids: 100
    security_opt:
      - no-new-privileges:true
      - seccomp=default
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:size=1G,mode=1777
    environment:
      - AGENT_ID=ops-agent-dev-001
      - AGENT_TYPE=ops_agent
      - MCP_SERVER_URL=http://mcp-server:8080
    volumes:
      - agent-workspace:/workspace:rw
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge

volumes:
  agent-workspace:
