name: agent-mvp-smoke
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      check_agent_faq:
        description: 'Also check POST /api/agent/faq'
        required: false
        default: 'false'

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Core smoke (healthz + billing)
        run: |
          set -e
          BASE="https://morningai-backend-v2.onrender.com"
          for ep in /healthz /api/billing/plans; do
            code=$(curl -s -o /dev/null -w "%{http_code}" "$BASE$ep")
            echo "$ep => $code"
            [ "$code" -eq 200 ] || (echo "::error::$ep expected 200, got $code" && exit 1)
          done
      - name: (Optional) Agent FAQ smoke (expect 202)
        if: ${{ github.event.inputs.check_agent_faq == 'true' }}
        run: |
          set -e
          BASE="https://morningai-backend-v2.onrender.com"
          code=$(curl -s -o /dev/null -w "%{http_code}" \
                -H 'Content-Type: application/json' \
                -d '{"question":"Generate FAQ"}' \
                "$BASE/api/agent/faq")
          echo "/api/agent/faq => $code"
          [ "$code" -eq 202 ] || (echo "::error::/api/agent/faq expected 202, got $code" && exit 1)
