name: agent-mvp-e2e
on:
  workflow_dispatch:
    inputs:
      test_sentry:
        description: 'Test Sentry integration (send smoke message)'
        required: false
        type: boolean
        default: false
  schedule:
    - cron: '0 2 * * *'

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          pip install requests PyGithub PyJWT
      
      - name: Run E2E Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_URL: https://morningai-backend-v2.onrender.com
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: |
          python - <<'EOF'
          import os
          import sys
          import time
          import requests
          from github import Github
          import jwt
          import datetime
          
          BASE = os.environ['BASE_URL']
          GITHUB_TOKEN = os.environ['GITHUB_TOKEN']
          JWT_SECRET = os.environ['JWT_SECRET_KEY']
          
          # Generate analyst JWT token for authentication
          analyst_payload = {
              'user_id': 2,
              'username': 'e2e-analyst',
              'role': 'analyst',
              'exp': datetime.datetime.utcnow() + datetime.timedelta(hours=1),
              'iat': datetime.datetime.utcnow()
          }
          token = jwt.encode(analyst_payload, JWT_SECRET, algorithm='HS256')
          
          print("=== Agent MVP E2E Test ===")
          
          print("\n1. Creating FAQ task...")
          response = requests.post(
              f"{BASE}/api/agent/faq",
              json={"question": "E2E test FAQ update"},
              headers={
                  "Content-Type": "application/json",
                  "Authorization": f"Bearer {token}"
              }
          )
          
          if response.status_code != 202:
              print(f"❌ Failed to create task: {response.status_code}")
              sys.exit(1)
          
          data = response.json()
          task_id = data.get('task_id')
          print(f"✅ Task created: {task_id}")
          
          print("\n2. Polling task status...")
          max_attempts = 60
          pr_url = None
          trace_id = None
          
          for attempt in range(max_attempts):
              time.sleep(5)
              response = requests.get(f"{BASE}/api/agent/tasks/{task_id}")
              
              if response.status_code != 200:
                  print(f"❌ Failed to get task status: {response.status_code}")
                  sys.exit(1)
              
              task = response.json()
              status = task.get('status')
              print(f"  Attempt {attempt + 1}: status={status}")
              
              if status == 'done':
                  pr_url = task.get('pr_url')
                  trace_id = task.get('trace_id')
                  print(f"✅ Task completed!")
                  print(f"   PR URL: {pr_url}")
                  print(f"   Trace ID: {trace_id}")
                  break
              elif status == 'error':
                  print(f"❌ Task failed: {task.get('error')}")
                  sys.exit(1)
          else:
              print("❌ Task did not complete in time")
              sys.exit(1)
          
          if pr_url:
              print("\n3. Verifying PR status...")
              gh = Github(GITHUB_TOKEN)
              repo = gh.get_repo("RC918/morningai")
              
              pr_number = int(pr_url.split('/')[-1])
              pr = repo.get_pull(pr_number)
              
              print(f"   PR #{pr_number}: {pr.title}")
              print(f"   State: {pr.state}")
              print(f"   Merged: {pr.merged}")
              
              if pr.state == 'open':
                  print("✅ PR is open (will be auto-merged by CI)")
              elif pr.merged:
                  print("✅ PR is already merged")
              else:
                  print(f"⚠️  PR state: {pr.state}")
          
          print("\n=== E2E Test Complete ===")
          EOF
      
      - name: Test Sentry Integration (Optional)
        if: github.event.inputs.test_sentry == 'true'
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          python - <<'EOF'
          import os
          import sys
          
          SENTRY_DSN = os.environ.get('SENTRY_DSN')
          
          if not SENTRY_DSN:
              print("⚠️  SENTRY_DSN not configured, skipping Sentry test")
              sys.exit(0)
          
          try:
              import sentry_sdk
              sentry_sdk.init(
                  dsn=SENTRY_DSN,
                  environment="ci-test",
                  traces_sample_rate=1.0,
              )
              
              event_id = sentry_sdk.capture_message(
                  "E2E Smoke Test - Sentry Integration",
                  level="info"
              )
              
              print(f"✅ Sentry smoke test successful")
              print(f"   Event ID: {event_id}")
              print(f"   Check Sentry dashboard for this event")
              
          except Exception as e:
              print(f"❌ Sentry smoke test failed: {e}")
              sys.exit(1)
          EOF
