name: agent-mvp-smoke
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Curl health & billing (GET)
        run: |
          set -e
          BASE="https://morningai-backend-v2.onrender.com"
          for ep in /healthz /api/billing/plans; do
            code=$(curl -s -o /dev/null -w "%{http_code}" "$BASE$ep")
            echo "$ep => $code"
            [ "$code" -eq 200 ] || (echo "::error::$ep expected 200, got $code" && exit 1)
          done
      
      - name: POST /api/billing/checkout/session expects 201
        run: |
          set -e
          BASE="https://morningai-backend-v2.onrender.com"
          code=$(curl -s -X POST -o /dev/null -w "%{http_code}" "$BASE/api/billing/checkout/session")
          echo "/api/billing/checkout/session (POST) => $code"
          [ "$code" -eq 201 ] || (echo "::error::POST /api/billing/checkout/session expected 201, got $code" && exit 1)
      
      - name: POST /api/agent/faq health check
        if: github.ref == 'refs/heads/main'
        run: |
          set -e
          BASE="https://morningai-backend-v2.onrender.com"
          code=$(curl -s -X POST -o /dev/null -w "%{http_code}" "$BASE/api/agent/faq" -H 'Content-Type: application/json' -d '{"topic":"smoke-test"}')
          echo "/api/agent/faq (POST) => $code"
          [ "$code" -eq 200 ] || (echo "::error::POST /api/agent/faq expected 200, got $code" && exit 1)
