name: backend-ci
on:
  push:
    paths: ["handoff/20250928/40_App/morningai_enhanced/api-backend/**", ".github/workflows/backend.yml"]
  pull_request:
    paths: ["handoff/20250928/40_App/morningai_enhanced/api-backend/**", ".github/workflows/backend.yml"]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: handoff/20250928/40_App/morningai_enhanced/api-backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install
        run: pip install -r requirements.txt
      - name: Lint (flake8 quick install)
        run: pip install flake8 && flake8 --ignore=E501 .
      - name: Smoke run (import app)
        run: python -c "import app; print('OK')"
