name: backend-ci
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.x'
      - name: Install dependencies
        run: |
          cd handoff/20250928/40_App/api-backend
          pip install -r requirements.txt
          pip install pytest pytest-cov
          cd ../orchestrator
          pip install -e .
      - name: Run tests with coverage
        env:
          REDIS_URL: redis://localhost:6379/0
        run: |
          cd handoff/20250928/40_App/api-backend
          python -m pytest --cov=src --cov-report=term-missing --cov-report=xml --cov-fail-under=43 -v
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: handoff/20250928/40_App/api-backend/coverage.xml
          retention-days: 30
