name: backend-ci
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.x'
      - name: Install dependencies
        run: |
          cd handoff/20250928/40_App/api-backend
          pip install -r requirements.txt
          pip install pytest pytest-cov
          cd ../orchestrator
          pip install -e .
      - name: Run tests with coverage
        run: |
          cd handoff/20250928/40_App/api-backend
          python -m pytest --cov=src --cov-report=term-missing --cov-fail-under=25 -v
