name: Ops Agent Sandbox E2E
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'handoff/20250928/40_App/orchestrator/sandbox/**'
      - 'handoff/20250928/40_App/orchestrator/mcp/**'
      - '.github/workflows/ops-agent-sandbox-e2e.yml'
      - 'docs/DEPLOYMENT_PROOF.md'
  pull_request:
    branches: [main]
    paths:
      - 'handoff/20250928/40_App/orchestrator/sandbox/**'
      - 'handoff/20250928/40_App/orchestrator/mcp/**'
      - '.github/workflows/ops-agent-sandbox-e2e.yml'
      - 'docs/DEPLOYMENT_PROOF.md'

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
    
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check if sandbox files exist and changed
        id: changed
        run: |
          # Check if required sandbox files exist
          if [ ! -f "handoff/20250928/40_App/orchestrator/sandbox/ops_agent/mcp_client.py" ] || \
             [ ! -f "handoff/20250928/40_App/orchestrator/sandbox/ops_agent/ops_agent_sandbox.py" ] || \
             [ ! -f "handoff/20250928/40_App/orchestrator/mcp/server.py" ]; then
            echo "run_tests=false" >> $GITHUB_OUTPUT
            echo "⚠️  Required sandbox files not found - skipping E2E tests (Phase 11 files may have been removed)"
            exit 0
          fi
          
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            git fetch origin ${{ github.base_ref }}
            CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -E '^(handoff/20250928/40_App/orchestrator/(sandbox|mcp)/|\.github/workflows/ops-agent-sandbox-e2e\.yml|docs/DEPLOYMENT_PROOF\.md)' || true)
            if [ -n "$CHANGED" ]; then
              echo "run_tests=true" >> $GITHUB_OUTPUT
              echo "Sandbox files changed, will run full E2E tests"
            else
              echo "run_tests=false" >> $GITHUB_OUTPUT
              echo "No sandbox files changed, skipping E2E tests"
            fi
          else
            echo "run_tests=true" >> $GITHUB_OUTPUT
            echo "Push to main or manual trigger, will run full E2E tests"
          fi
      
      - name: Setup Python
        if: steps.changed.outputs.run_tests == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.x'
      
      - name: Install flyctl
        if: steps.changed.outputs.run_tests == 'true'
        uses: superfly/flyctl-actions/setup-flyctl@v1
      
      - name: Install dependencies
        if: steps.changed.outputs.run_tests == 'true'
        run: |
          cd handoff/20250928/40_App/orchestrator
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install -e .
      
      - name: Install Playwright browsers
        if: steps.changed.outputs.run_tests == 'true'
        run: |
          npx playwright install --with-deps chromium
      
      - name: Deploy ephemeral sandbox to Fly.io
        if: steps.changed.outputs.run_tests == 'true'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          export APP_NAME="morningai-sandbox-e2e-${{ github.run_id }}"
          echo "Deploying ephemeral sandbox: $APP_NAME"
          
          cd handoff/20250928/40_App/orchestrator/sandbox/ops_agent
          
          echo "Copying mcp module into build context..."
          cp -r ../../mcp .
          
          flyctl apps create $APP_NAME --org personal || true
          
          flyctl deploy \
            --app $APP_NAME \
            --primary-region sin \
            --vm-size shared-cpu-1x \
            --vm-memory 256 \
            --wait-timeout 300
          
          echo "SANDBOX_APP_NAME=$APP_NAME" >> $GITHUB_ENV
          
          SANDBOX_URL=$(flyctl status --app $APP_NAME --json | jq -r '.Hostname')
          echo "SANDBOX_URL=https://$SANDBOX_URL" >> $GITHUB_ENV
          echo "Sandbox deployed at: https://$SANDBOX_URL"
      
      - name: Verify sandbox deployment
        if: steps.changed.outputs.run_tests == 'true'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          echo "Verifying sandbox deployment status..."
          flyctl status --app ${{ env.SANDBOX_APP_NAME }}
          
          echo "Checking sandbox health..."
          flyctl checks list --app ${{ env.SANDBOX_APP_NAME }}
          
          echo "Viewing recent logs..."
          flyctl logs --app ${{ env.SANDBOX_APP_NAME }} -n
      
      - name: Start MCP Server
        if: steps.changed.outputs.run_tests == 'true'
        run: |
          cd handoff/20250928/40_App/orchestrator
          python mcp/server.py > /tmp/mcp-server.log 2>&1 &
          sleep 5
          echo "MCP Server started, checking logs..."
          cat /tmp/mcp-server.log || true
      
      - name: Run E2E test
        if: steps.changed.outputs.run_tests == 'true'
        env:
          SANDBOX_ENABLED: 'true'
          SANDBOX_URL: ${{ env.SANDBOX_URL }}
          REDIS_URL: redis://localhost:6379
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: RC918/morningai
        run: |
          cd handoff/20250928/40_App/orchestrator
          python -m pytest tests/test_ops_agent_sandbox.py -v --tb=long --log-cli-level=INFO 2>&1 | tee /tmp/pytest-output.log
      
      - name: Skip E2E tests (no sandbox changes)
        if: steps.changed.outputs.run_tests == 'false'
        run: |
          echo "✅ Sandbox files unchanged - skipping expensive Fly.io deployment"
          echo "This check passes automatically for PRs that don't modify sandbox code"
      
      - name: Cleanup ephemeral sandbox
        if: always() && steps.changed.outputs.run_tests == 'true'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          if [ -n "${{ env.SANDBOX_APP_NAME }}" ]; then
            echo "Destroying ephemeral sandbox: ${{ env.SANDBOX_APP_NAME }}"
            flyctl apps destroy ${{ env.SANDBOX_APP_NAME }} --yes || true
          fi
      
      - name: Upload test logs
        if: always() && steps.changed.outputs.run_tests == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-logs
          path: |
            /tmp/pytest-output.log
            /tmp/mcp-server.log
          retention-days: 7
