name: orchestrator-e2e
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python handoff/20250928/40_App/orchestrator/graph.py --goal "demo task"
