name: orchestrator-e2e
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.x'
      - name: Install orchestrator dependencies
        run: |
          cd handoff/20250928/40_App/orchestrator
          pip install -r requirements.txt
          pip install -e .
      - name: Run orchestrator demo
        run: |
          cd handoff/20250928/40_App/orchestrator
          python graph.py --goal "demo task"
