name: Post-Deploy Health Assertions
on:
  workflow_dispatch:
  push: { branches: [ main ] }
  schedule:
    - cron: "0 * * * *"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check core health (/healthz)
        run: |
          set -e
          curl -sS https://morningai-backend-v2.onrender.com/healthz | tee /tmp/health.json
          jq -e '
            (.phase | test("Phase 8")) and
            ((.version // .app_version // .app_version_tag // .app_build // "") | test("^8\\.0\\.0$")) and
            ((.status // "") | test("healthy") or (.database // "") | test("connected"))
          ' /tmp/health.json >/dev/null

      - name: Test Phase 4–6 API endpoints (JWT optional)
        env:
          TEST_ADMIN_JWT: ${{ secrets.TEST_ADMIN_JWT }}
        run: |
          set -e
          BASE="https://morningai-backend-v2.onrender.com"
          # Phase 4 & 5 要 200
          for EP in /api/governance/status /api/business-intelligence/summary; do
            code=$(curl -s -o /dev/null -w "%{http_code}" "$BASE$EP")
            test "$code" -eq 200 || { echo "$EP code=$code"; exit 1; }
          done
          # Phase 6：有 JWT 期待 200，沒有 JWT 允許 401（保護生效）
          if [ -n "$TEST_ADMIN_JWT" ]; then
            code=$(curl -s -H "Authorization: Bearer $TEST_ADMIN_JWT" -o /dev/null -w "%{http_code}" "$BASE/api/security/reviews/pending")
            test "$code" -eq 200 || { echo "/api/security/reviews/pending code=$code (expect 200 with JWT)"; exit 1; }
          else
            code=$(curl -s -o /dev/null -w "%{http_code}" "$BASE/api/security/reviews/pending")
            test "$code" -eq 200 -o "$code" -eq 401 || { echo "/api/security/reviews/pending code=$code (expect 200 or 401)"; exit 1; }
          fi

      - name: SLA Baseline (success-rate & latency)
        run: |
          URL="https://morningai-backend-v2.onrender.com/health"; TOTAL=10; S=0; T=0
          for i in $(seq 1 $TOTAL); do
            o=$(curl -s -o /dev/null -w '%{http_code} %{time_total}\n' "$URL"); c=${o% *}; d=${o#* }
            [ "$c" -eq 200 ] && S=$((S+1))
            T=$(awk -v a=$T -v b=$d 'BEGIN{printf "%.6f", a+b}')
          done
          RATE=$((S*100/TOTAL)); AVG=$(awk -v T=$T -v N=$TOTAL 'BEGIN{printf "%.3f", T/N}')
          echo "rate=$RATE avg=${AVG}s"
          test "$RATE" -ge 90
