name: secret-scan
on: {pull_request: {}, push: {branches: [main]}, workflow_dispatch: {}}
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2
