name: Secret Scanning

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for comprehensive scan

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}  # Optional: for Gitleaks Pro features

      - name: Upload Gitleaks Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
          retention-days: 7

  trufflehog:
    name: TruffleHog Secret Scan
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for comprehensive scan

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: TruffleHog Scan (Full Repository)
        if: github.event_name == 'workflow_dispatch'
        run: |
          docker run --rm -v "$PWD:/pwd" trufflesecurity/trufflehog:latest \
            filesystem /pwd \
            --json \
            --no-update \
            > trufflehog-report.json || true

      - name: Upload TruffleHog Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-report
          path: trufflehog-report.json
          retention-days: 7
          if-no-files-found: ignore

  security-summary:
    name: Security Scan Summary
    runs-on: ubuntu-latest
    needs: [gitleaks, trufflehog]
    if: always()
    steps:
      - name: Check scan results
        run: |
          echo "## 🔒 Secret Scanning Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ needs.gitleaks.result }}" == "success" ]; then
            echo "✅ **Gitleaks**: No secrets detected" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Gitleaks**: Secrets detected! Review the logs." >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ needs.trufflehog.result }}" == "success" ]; then
            echo "✅ **TruffleHog**: No verified secrets detected" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ **TruffleHog**: Potential secrets detected! Review the logs." >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📋 Next Steps" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "If secrets were detected:" >> $GITHUB_STEP_SUMMARY
          echo "1. **DO NOT** commit the secrets" >> $GITHUB_STEP_SUMMARY
          echo "2. Rotate all exposed credentials immediately" >> $GITHUB_STEP_SUMMARY
          echo "3. Use environment variables or secret management" >> $GITHUB_STEP_SUMMARY
          echo "4. Add false positives to .gitleaksignore" >> $GITHUB_STEP_SUMMARY
          
          # Fail if either scan failed
          if [ "${{ needs.gitleaks.result }}" != "success" ]; then
            echo "::error::Gitleaks detected secrets in the codebase"
            exit 1
          fi

  # Block PR merge if secrets are detected
  block-merge:
    name: Block Merge on Secret Detection
    runs-on: ubuntu-latest
    needs: [gitleaks, trufflehog]
    if: github.event_name == 'pull_request'
    steps:
      - name: Check for secrets
        run: |
          if [ "${{ needs.gitleaks.result }}" != "success" ]; then
            echo "::error::❌ PR blocked: Secrets detected by Gitleaks"
            echo "Please remove all secrets before merging."
            exit 1
          fi
          
          echo "✅ No secrets detected - PR can be merged"
