name: vercel-deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel
        run: echo "Vercel deployment placeholder"
