name: Worker Heartbeat Monitor
on:
  schedule: [{ cron: '*/15 * * * *' }]
  workflow_dispatch:
permissions:
  contents: read
  issues: write
jobs:
  check-heartbeat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: pip install redis
      - name: Check worker heartbeats
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: python .github/scripts/check_heartbeat.py
      - if: failure()
        name: Create issue on heartbeat failure
        uses: dacbd/create-issue-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "⚠️ Worker Heartbeat Alert: Missing heartbeats detected"
          body: "Auto-opened by monitor. See run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
